import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'
import { execFileSync } from 'node:child_process'

const artifacts=path.resolve('../browser_artifacts/screenshots')

async function monitor(page) {
  const errors=[]
  page.on('pageerror',error=>errors.push(`page: ${error.message}`))
  page.on('console',message=>{if(message.type()==='error')errors.push(`console: ${message.text()}`)})
  page.on('response',response=>{if(response.status()>=500)errors.push(`HTTP ${response.status()}: ${response.url()}`)})
  return errors
}

async function loadDemo(page) {
  await page.goto('/investigations/demo')
  await page.waitForURL(/\/investigations\/[0-9a-f-]+$/)
  await expect(page.getByText('Fredericella sultana').first()).toBeVisible()
}

test.beforeAll(async()=>mkdir(artifacts,{recursive:true}))

test('homepage navigation and verified map render without errors', async ({page},testInfo) => {
  const errors=await monitor(page)
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'From uncertain DNA detections to clearer freshwater decisions.'})).toBeVisible()
  await expect(page.locator('.home-map .maplibregl-canvas').first()).toBeVisible()
  await expect(page.locator('.home-map').first().getByText('Verified HydroRIVERS geometry · EPSG:4326')).toBeVisible()
  await expect(page.getByRole('link',{name:'Dashboard'})).toHaveAttribute('href','/dashboard')
  await page.screenshot({path:path.join(artifacts,`home-${testInfo.project.name}.png`),fullPage:true})
  expect(errors).toEqual([])
})

test('Wigger workspace exposes the historical observation, map controls, decision, and trace', async ({page},testInfo) => {
  const errors=await monitor(page)
  await loadDemo(page)
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await expect(page.locator('.zone-grid > div')).toHaveCount(3)
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await expect(page.locator('.workspace-map .maplibre-site-marker')).toHaveCount(4)
  await expect(page.getByText('2014-06-25',{exact:true})).toBeVisible()
  await expect(page.getByText('Observation index').locator('..')).toContainText('4')
  await expect(page.getByText('1.2983219767633366e-17 mol/L')).toBeVisible()
  await expect(page.getByText('DETECTED')).toBeVisible()
  await expect(page.locator('.workspace-map .maplibregl-canvas')).toBeVisible()
  await expect(page.locator('.workspace-map .maplibre-site-marker')).toHaveCount(4)

  const map=page.locator('.workspace-map .scientific-map')
  await map.getByRole('button',{name:'Zoom in'}).click()
  await map.getByRole('button',{name:'Reset map view'}).click()
  await map.getByLabel('Select Site B').press('Enter')
  await expect(map.getByRole('status')).toContainText('Reach 20450127')
  await map.getByRole('checkbox',{name:'River network'}).uncheck()
  await map.getByRole('checkbox',{name:'River network'}).check()
  await map.getByRole('button',{name:'Toggle fullscreen'}).click()
  await expect(map).toHaveClass(/map-fullscreen/)
  await map.getByRole('button',{name:'Toggle fullscreen'}).click()

  await page.getByRole('button',{name:/Next Steps/}).click()
  await expect(page.getByText('Register a real follow-up sample')).toBeVisible()
  await page.getByRole('button',{name:'Evaluate sampling decision'}).click()
  await expect(page.getByText('Loading scientific investigation')).toBeHidden()
  await expect(page.getByText('TIE').first()).toBeVisible()
  await expect(page.getByRole('heading',{name:'Decision trace'})).toBeVisible()
  await expect(page.getByText(/sampling\.topology_pair_separation\.v1/)).toBeVisible()
  await page.screenshot({path:path.join(artifacts,`workspace-${testInfo.project.name}.png`),fullPage:true})
  expect(errors).toEqual([])
})

test('site filtering keeps list, markers, and details synchronized', async ({page},testInfo) => {
  await page.goto('/sites')
  await expect(page.locator('.site-cards button')).toHaveCount(4)
  await page.locator('.site-cards button').filter({hasText:'Site C'}).click()
  await expect(page.locator('.site-details')).toContainText('20451169')
  await page.getByLabel('Site type').selectOption({label:'Candidate sample'})
  await expect(page.locator('.site-cards button')).toHaveCount(3)
  await expect(page.locator('.scientific-map .maplibre-site-marker')).toHaveCount(3)
  await expect(page.locator('.site-details h3')).toHaveText('Site C')
  await page.getByPlaceholder('Search sites').fill('Site D')
  await expect(page.locator('.site-cards button')).toHaveCount(1)
  await expect(page.locator('.site-details h3')).toHaveText('Site D')
  await expect(page.locator('.site-details')).toContainText('20448315')
  await page.screenshot({path:path.join(artifacts,`sites-${testInfo.project.name}.png`),fullPage:true})
})

test('responsive pages have no document-level horizontal overflow', async ({page},testInfo) => {
  await loadDemo(page)
  const casePath=new URL(page.url()).pathname
  for (const [name,url] of [['dashboard','/dashboard'],['investigations','/investigations'],['sites','/sites'],['workspace',casePath],['reports','/reports']]) {
    await page.goto(url)
    // Map tile requests need not become idle; wait for the application data under test.
    if(name==='dashboard')await expect(page.getByText('Persisted ACTIVE cases').locator('..').locator('b')).toHaveText(/^\d+$/)
    if(name==='investigations')await expect(page.locator('tbody tr').first()).toBeVisible()
    if(name==='sites'||name==='workspace')await expect(page.locator('.maplibregl-canvas').first()).toBeVisible()
    if(name==='reports'){
      await page.getByLabel('Scientific report').selectOption({label:'Wigger River Investigation'})
      await expect(page.getByText('1.2983219767633366e-17 mol/L')).toBeVisible()
    }
    const dimensions=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth])
    expect(dimensions[0],`${name} overflow at ${testInfo.project.name}`).toBeLessThanOrEqual(dimensions[1])
  }
  await page.screenshot({path:path.join(artifacts,`report-${testInfo.project.name}.png`),fullPage:true})
})

test('desktop workflow validates creation, filters records, and prints the report', async ({page},testInfo) => {
  test.skip(testInfo.project.name!=='desktop-1440','Full interaction runs once at desktop size')
  await loadDemo(page)
  await page.getByRole('button',{name:'Evaluate sampling decision'}).click()
  await expect(page.getByRole('heading',{name:'Decision trace'})).toBeVisible()

  await page.goto('/investigations/new')
  await page.getByRole('button',{name:'Create investigation'}).click()
  await expect(page.getByText('Required')).toHaveCount(6)
  await page.getByLabel('Investigation name').fill('Browser verification case')
  await page.getByLabel('Target species').fill('Browser verification test taxon')
  await page.getByLabel('Latitude').fill('47.314')
  await page.getByLabel('Longitude').fill('7.8954')
  await page.getByLabel('Verified HydroRIVERS reach ID').fill('999999999')
  await page.locator('.investigation-form').getByLabel('Date').fill('2026-10-02')
  await page.getByRole('button',{name:'Create investigation'}).click()
  await expect(page.locator('.form-notice')).toContainText('not found in loaded network data')
  await page.getByLabel('Verified HydroRIVERS reach ID').fill('20446064')
  await page.getByLabel('Replicate 1').selectOption('Negative')
  await page.getByRole('button',{name:'Create investigation'}).click()
  await page.waitForURL(/\/investigations\/[0-9a-f-]+$/)
  await expect(page.locator('.workspace-map .maplibregl-canvas')).toBeVisible()
  await expect(page.locator('.workspace-map .maplibre-site-marker')).toHaveCount(1)
  await expect(page.getByText('NOT EVALUATED').first()).toBeVisible()
  await expect(page.getByText('No candidate zones are registered.')).toBeVisible()
  await page.getByRole('button',{name:/Next Steps/}).click()
  await expect(page.getByText('No follow-up samples have been registered.')).toBeVisible()
  await page.getByRole('button',{name:'Register follow-up sample',exact:true}).locator('..').locator('select').selectOption({label:'Detection Site'})
  await page.locator('.follow-up-form input[type="datetime-local"]').fill('2026-10-02T10:00')
  await page.getByPlaceholder('Assay').fill('Browser test assay')
  await page.getByPlaceholder('Controls status').fill('Passed')
  await page.getByPlaceholder('Collector source').fill('Browser verification')
  await page.getByRole('button',{name:'Register follow-up sample'}).click()
  await expect(page.getByText('Browser test assay')).toBeVisible()

  await page.goto('/investigations')
  await page.getByLabel('Search investigations').fill('Browser verification case')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.getByText('NOT EVALUATED')).toBeVisible()
  await page.getByText('Clear filters').click()
  await page.getByLabel('Scientific decision').selectOption('TIE')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.locator('tbody tr')).toContainText('Fredericella sultana')

  await page.goto('/dashboard')
  await expect(page.getByText('Persisted ACTIVE cases').locator('..').locator('b')).toHaveText('2')
  await expect(page.getByText('Cases without a persisted decision').locator('..').locator('b')).toHaveText('1')

  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption({label:'Wigger River Investigation'})
  await expect(page.getByText('1.2983219767633366e-17 mol/L')).toBeVisible()
  await expect(page.getByText('hydrorivers.directed_contribution.v1').first()).toBeVisible()
  await expect(page.locator('.report-document .maplibregl-canvas')).toBeVisible()
  await expect(page.locator('#assumptions')).toContainText('remaining hypotheses')
  await expect(page.locator('#followup')).toContainText('Site B, Site C, Site D')
  await page.locator('.report-toc').getByRole('button',{name:'Limitations',exact:true}).click()
  await expect(page.locator('#limitations')).toBeInViewport()
  await page.emulateMedia({media:'print'})
  await expect(page.locator('.app-nav')).toBeHidden()
  await page.pdf({path:path.resolve('../browser_artifacts/WIGGER_BROWSER_REPORT.pdf'),format:'A4',printBackground:true})
})

test('frontend presents API failures as errors rather than empty records', async ({page},testInfo) => {
  test.skip(testInfo.project.name!=='desktop-1440','Failure-path checks run once')
  await page.route('**/cases',route=>route.abort('failed'))
  await page.goto('/dashboard')
  await expect(page.getByText('Could not load investigations')).toBeVisible()
  await page.unroute('**/cases')
  await page.goto('/investigations/not-a-uuid')
  await expect(page.getByText('Investigation unavailable')).toBeVisible()
  await page.route('**/demo/wigger/map',route=>route.fulfill({status:500,contentType:'application/json',body:'{"error":{"message":"map unavailable"}}'}))
  await page.goto('/sites')
  await expect(page.getByText('Map service unavailable')).toBeVisible()
})

test('replicate editing, atomic failure, reference import and selected report export',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Repair regression runs once')
  await page.goto('/investigations/new')
  await page.getByLabel('Investigation name').fill('Replicate repair demonstration')
  await page.getByLabel('Target species').fill('Recorded test taxon')
  await page.getByLabel('Latitude').fill('47.3140004')
  await page.getByLabel('Longitude').fill('7.8954007')
  await page.getByLabel('Verified HydroRIVERS reach ID').fill('20446064')
  await page.locator('.investigation-form').getByLabel('Date').fill('2026-10-02')
  await page.getByLabel('Replicate 1').selectOption('Positive')
  await page.getByRole('button',{name:'Add replicate',exact:true}).click()
  await page.getByLabel('Replicate 2').selectOption('Negative')
  await page.getByRole('button',{name:'Add replicate',exact:true}).click()
  await page.getByLabel('Replicate 3').selectOption('Positive')
  await page.getByLabel('Replicate 3').selectOption('Invalid')
  await page.getByRole('button',{name:'Add replicate',exact:true}).click()
  await page.getByRole('button',{name:'Remove replicate 4',exact:true}).click()
  await page.getByLabel('Laboratory or assay metadata').fill('Recorded assay metadata XYZ')
  let submissions=0
  await page.route('**/cases',async route=>{
    if(route.request().method()==='POST'){
      submissions++
      expect(route.request().postDataJSON().initial_evidence[0].value.replicate_results).toEqual(['Positive','Negative','Invalid'])
      await route.fulfill({status:500,contentType:'application/json',body:'{"detail":"initial evidence failed; transaction rolled back"}'})
    }else await route.continue()
  })
  await page.getByRole('button',{name:'Create investigation',exact:true}).click()
  await expect(page.locator('.form-notice')).toContainText('transaction rolled back')
  expect(submissions).toBe(1)
  await expect(page.getByLabel('Replicate 3')).toHaveValue('Invalid')
  await page.unroute('**/cases')
  await page.getByRole('button',{name:'Create investigation',exact:true}).click()
  await page.waitForURL(/\/investigations\/[0-9a-f-]+$/)
  const caseId=page.url().split('/').at(-1)
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await expect(page.locator('.zone-grid > div').filter({hasText:'Root reach 20447392'})).toContainText('Network validation: VERIFIED')
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await expect(page.locator('.zone-grid > div')).toHaveCount(3)
  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption(caseId)
  await expect(page.locator('.report-document header')).toContainText('Replicate repair demonstration')
  for(const value of ['Positive','Negative','Invalid','Recorded assay metadata XYZ','USER_ENTERED'])await expect(page.locator('#evidence')).toContainText(value)
  await expect(page.locator('#summary')).toContainText('Draft — missing or unavailable')
  await page.evaluate(()=>{window.__printed=false;window.print=()=>{window.__printed=true}})
  await expect(page.getByRole('button',{name:'Export PDF'})).toBeEnabled()
  await page.getByRole('button',{name:'Export PDF'}).click()
  await expect.poll(()=>page.evaluate(()=>window.__printed)).toBe(true)
  await page.emulateMedia({media:'print'})
  await page.pdf({path:path.resolve('../browser_artifacts/REPLICATE_REPAIR_REPORT.pdf'),format:'A4',printBackground:true})
})

test('dependent index failure displays unavailable metrics',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Repair regression runs once')
  await page.route('**/cases/*/follow-up-samples',route=>route.fulfill({status:503,contentType:'application/json',body:'{"detail":"follow-up service unavailable"}'}))
  await page.goto('/dashboard')
  await expect(page.getByText('Could not load investigations')).toBeVisible()
  await expect(page.locator('.metric b')).toHaveText(['—','—','—','—'])
  await expect(page.getByText('No investigation records are available yet.')).toHaveCount(0)
  await page.goto('/investigations')
  await expect(page.getByText('Backend unavailable')).toBeVisible()
})

test('new validated Wigger investigation completes scientific workflow and PDF export',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Complete workflow runs once')
  await page.goto('/investigations/new')
  await page.getByLabel('Investigation name').fill('Complete Wigger workflow')
  await page.getByLabel('Target species').fill('Fredericella sultana')
  await page.getByLabel('Latitude').fill('47.3140004')
  await page.getByLabel('Longitude').fill('7.8954007')
  await page.getByLabel('Verified HydroRIVERS reach ID').fill('20446064')
  await page.locator('.investigation-form').getByLabel('Date').fill('2014-06-25')
  await page.getByLabel('Replicate 1').selectOption('Positive')
  await page.getByRole('button',{name:'Add replicate',exact:true}).click()
  await page.getByLabel('Replicate 2').selectOption('Positive')
  await page.getByRole('button',{name:'Add replicate',exact:true}).click()
  await page.getByLabel('Replicate 3').selectOption('Negative')
  await page.getByRole('button',{name:'Create investigation',exact:true}).click()
  await page.waitForURL(/\/investigations\/[0-9a-f-]+$/)
  const caseId=page.url().split('/').at(-1)
  await expect(page.getByText('Detection validation: MATCHED')).toBeVisible()
  await expect(page.getByText(/Observation coordinates and reach match frozen Wigger/)).toBeVisible()
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await expect(page.locator('.zone-grid > div')).toHaveCount(3)
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await expect(page.locator('.zone-grid > div')).toHaveCount(3)
  await page.getByRole('button',{name:'Generate candidate comparison'}).click()
  await expect(page.locator('.investigation-panel .table-scroll tbody tr')).toHaveCount(4)
  await page.getByRole('button',{name:'Evaluate sampling decision'}).click()
  await expect(page.getByRole('heading',{name:'Decision trace'})).toBeVisible()
  await expect(page.locator('.workspace-heading')).toContainText('TIE')
  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption(caseId)
  await expect(page.locator('#detection')).toContainText('2014-06-25')
  await expect(page.locator('#detection')).toContainText('MATCHED')
  await expect(page.locator('#detection')).toContainText('manual')
  await expect(page.locator('#detection table').nth(1).locator('tbody tr')).toHaveCount(3)
  await expect(page.locator('#sources tbody tr')).toHaveCount(3)
  await expect(page.locator('#candidates tbody tr')).toHaveCount(4)
  await expect(page.locator('#decision')).toContainText('Rules applied:')
  await expect(page.locator('#decision')).not.toContainText('Decision trace ID:')
  await expect(page.locator('#followup')).toContainText('Site B, Site C, Site D')
  await page.evaluate(()=>{window.__printed=false;window.print=()=>{window.__printed=true}})
  await page.getByRole('button',{name:'Export PDF'}).click()
  await expect.poll(()=>page.evaluate(()=>window.__printed)).toBe(true)
  await page.emulateMedia({media:'print'})
  await page.pdf({path:path.resolve('../browser_artifacts/COMPLETE_WIGGER_REPORT.pdf'),format:'A4',printBackground:true})
})

test('legacy comparison displays availability without inventing scores',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Focused legacy response regression')
  const demo=await (await page.request.get('http://127.0.0.1:18001/demo/wigger')).json()
  const decision=await (await page.request.post(`http://127.0.0.1:18001/cases/${demo.case_id}/sampling-decision`)).json()
  const limitation='Historical candidate comparison is incomplete; it was not reconstructed.'
  await page.route(`**/cases/${demo.case_id}/sampling-decision`,route=>route.fulfill({json:{
    ...decision,candidate_scope:'REGISTERED_SITES',
    candidate_snapshot:{candidates:[{site_id:null,hyriv_id:20450127,signature:null,pair_separation_score:null}]},
    compatibility:{status:'PARTIAL',candidate_comparison_available:false,limitations:[limitation]},
  }}))
  await page.goto(`/investigations/${demo.case_id}`)
  await expect(page.getByText(`Historical data is incomplete: ${limitation}`)).toBeVisible()
  await expect(page.locator('.investigation-panel .table-scroll')).toContainText('Unavailable')
  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption(demo.case_id)
  await expect(page.locator('#summary')).toContainText(limitation)
  await expect(page.locator('#candidates')).toContainText('Unavailable')
})

test('TIE field planning, candidate follow-up, versioned report and printable scientific context',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Focused functional completion workflow')
  await loadDemo(page)
  await page.getByRole('button',{name:'Evaluate sampling decision'}).click()
  await expect(page.getByRole('heading',{name:'TIE monitoring alternatives'})).toBeVisible()
  const plan=page.locator('.tie-monitoring-plan')
  await expect(plan).toContainText('None has a superior scientific score')
  await expect(plan).toContainText('Unresolved hypothesis pairs')
  await plan.getByLabel('Monitoring alternative').selectOption({label:'Site B'})
  await plan.getByLabel('Researcher or team').fill('Synthetic QA field team')
  await plan.getByLabel('accessibility',{exact:true}).fill('Synthetic accessible-bank observation')
  await plan.getByLabel('field restrictions',{exact:true}).fill('Synthetic permission required')
  await plan.getByRole('button',{name:'Save field choice'}).click()
  await expect(page.locator('.workspace-heading')).toContainText('TIE')
  await expect(page.locator('.tie-monitoring-plan')).toContainText('Researcher-selected field site: reach 20450127')
  const caseId=page.url().split('/').at(-1)
  const stored=await (await page.request.get(`http://127.0.0.1:18001/cases/${caseId}/sampling-decision`)).json()
  expect(stored.status).toBe('TIE')
  expect(stored.candidate_snapshot.candidates.filter(candidate=>stored.recommended_site_ids.includes(candidate.site_id)).map(candidate=>candidate.pair_separation_score)).toEqual([2,2,2])
  await page.getByRole('button',{name:/Next Steps/}).click()
  const sample=page.getByRole('button',{name:'Register follow-up sample'}).locator('..')
  await sample.locator('select').selectOption('candidate:20450127')
  await sample.locator('input[type="datetime-local"]').fill('2024-01-01T10:00')
  await sample.getByPlaceholder('Assay',{exact:true}).fill('Synthetic regression assay')
  await sample.getByPlaceholder('Controls status').fill('PASS')
  await sample.getByPlaceholder('Collector source').fill('Synthetic QA field team')
  await sample.getByRole('button',{name:'Register follow-up sample'}).click()
  await expect(page.getByRole('button',{name:'Run reinvestigation'})).toBeEnabled()
  const samples=await (await page.request.get(`http://127.0.0.1:18001/cases/${caseId}/follow-up-samples`)).json()
  expect(samples.some(item=>item.hyriv_id===20450127&&item.candidate_reference)).toBe(true)
  for(let index=0;index<2;index++){
    await page.getByRole('button',{name:'Run reinvestigation'}).click()
    await expect(page.getByRole('button',{name:'Run reinvestigation'})).toBeEnabled()
  }
  await page.route(`**/cases/${caseId}/context`,route=>route.fulfill({json:[{
    provider:'Synthetic offline provider',status:'ERROR',error:'Synthetic provider timeout',
    limitations:['Synthetic context could not be established'],compatibility:'UNKNOWN',strength:'UNASSESSED',
  }]}))
  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption(caseId)
  await expect(page.locator('#context')).toContainText('Synthetic provider timeout')
  await expect(page.locator('#context')).toContainText('ERROR')
  await expect(page.locator('#context')).toContainText('10.1007/s00436-006-0371-0')
  await expect(page.locator('#context')).toContainText('10.3390/pathogens9010016')
  await expect(page.locator('#context')).toContainText('UNKNOWN')
  await expect(page.locator('#history')).toContainText('Comparison availability: AVAILABLE')
  await expect(page.locator('#history')).toContainText('No scientifically supported hypothesis, candidate, or decision change occurred')
  await expect(page.locator('#decision')).toContainText('Scientific rule versions:')
  await expect(page.locator('#monitoring')).toContainText('Pair-separation score: 2')
  await page.emulateMedia({media:'print'})
  const pdf=path.resolve('../browser_artifacts/FUNCTIONAL_COMPLETION_REPORT.pdf')
  await page.pdf({path:pdf,format:'A4',printBackground:true})
  const printed=execFileSync('pdftotext',[pdf,'-'],{encoding:'utf8'}).replace(/\s+/g,' ')
  for(const section of ['Actionable TIE Monitoring Plan','Versioned Reinvestigation History','10.3390/pathogens9010016','Synthetic provider timeout','Scientific rule versions'])expect(printed).toContain(section)
})

test('normal UI hides UUIDs and separates network, evidence and hypothesis status with persisted distances',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Targeted scientific data-pipeline regression')
  const api='http://127.0.0.1:18001'
  const created=await page.request.post(`${api}/cases`,{data:{
    target_taxon:'Fredericella sultana',observation_date:'2014-06-25',
    detection_site_latitude:47.3140004,detection_site_longitude:7.8954007,detection_site_hyriv_id:20446064,
    metadata:{name:'UI pipeline regression'},
    initial_evidence:[{evidence_type:'edna_observation',source:'Synthetic regression record',
      value:{replicate_results:['Positive','Negative']},provenance:{synthetic:true}}],
  }})
  expect(created.status()).toBe(201)
  const record=await created.json(), id=record.id
  expect((await page.request.post(`${api}/cases/${id}/wigger-reference`)).ok()).toBe(true)
  await page.goto('/investigations')
  await expect(page.getByRole('columnheader',{name:'Investigation',exact:true})).toBeVisible()
  const uuid=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i
  expect(await page.locator('tbody').innerText()).not.toMatch(uuid)
  await page.getByLabel('Search investigations').fill('UI pipeline regression')
  const row=page.locator('tbody tr').filter({hasText:'UI pipeline regression'})
  await expect(row).toHaveCount(1)
  await row.getByRole('link',{name:'Open',exact:true}).click()
  await page.waitForURL(`**/investigations/${id}`)
  const sources=page.locator('.zone-grid > div')
  await expect(sources).toHaveCount(3)
  for(const source of await sources.all()){
    await expect(source).toContainText('Network validation: VERIFIED')
    await expect(source).toContainText('Evidence compatibility: UNKNOWN')
    await expect(source).toContainText('Hypothesis state: UNKNOWN')
    await expect(source).toContainText('No validated scientific rule applies')
    await expect(source).toContainText('not a biological source')
  }
  await page.getByRole('button',{name:'Evaluate sampling decision'}).click()
  await expect(page.getByRole('heading',{name:'Decision trace'})).toBeVisible()
  const table=page.locator('.investigation-panel .table-scroll').first()
  for(const distance of ['19.226 km','23.936 km','10.941 km'])await expect(table).toContainText(distance)
  await expect(table).toContainText('Validated reference')
  const decision=await (await page.request.get(`${api}/cases/${id}/sampling-decision`)).json()
  expect(decision.status).toBe('TIE')
  expect(decision.candidate_snapshot.candidates.filter(c=>decision.recommended_site_ids.includes(c.site_id)).map(c=>c.pair_separation_score)).toEqual([2,2,2])
  expect(await page.locator('.investigation-panel').innerText()).not.toMatch(uuid)
  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption(id)
  await expect(page.locator('#candidates')).toContainText('19.226 km')
  expect(await page.locator('.report-document').innerText()).not.toMatch(uuid)
  await page.goto('/dashboard')
  await expect(page.locator('.recent')).toContainText('UI pipeline regression')
  expect(await page.locator('.recent').innerText()).not.toMatch(uuid)
  const unnamed=await page.request.post(`${api}/cases`,{data:{target_taxon:'Synthetic unnamed case',observation_date:'2014-06-25',
    detection_site_latitude:47.3140004,detection_site_longitude:7.8954007,detection_site_hyriv_id:20446064,metadata:{}}})
  expect(unnamed.status()).toBe(201)
  await page.goto('/investigations')
  await page.getByLabel('Search investigations').fill('Unnamed investigation')
  await expect(page.locator('tbody')).toContainText('Unnamed investigation')
  expect(await page.locator('tbody').innerText()).not.toMatch(uuid)
  // A stored unsupported path is displayed with its specific reason.
  const reason='No directed downstream path from candidate position to detection position in the loaded network.'
  await page.route(`**/cases/${id}/sampling-decision`,route=>route.fulfill({json:{...decision,
    candidate_snapshot:{candidates:decision.candidate_snapshot.candidates.map(c=>({...c,network_distance_km:null,
      network_distance_status:'UNAVAILABLE',network_distance_reason:reason}))}}}))
  await page.goto(`/investigations/${id}`)
  await expect(page.locator('.investigation-panel .table-scroll').first()).toContainText(reason)
})


test('multispecies creation, independent decisions, map matching and context-scoped PDF',async ({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-1440','Multispecies context workflow runs once')
  const api='http://127.0.0.1:18001'
  await page.goto('/investigations/new')
  await page.getByLabel('Investigation name').fill('Multispecies scientific regression')
  await page.getByLabel('Target species',{exact:true}).fill('Fredericella sultana')
  await page.getByLabel('Latitude',{exact:true}).fill('47.3140004')
  await page.getByLabel('Longitude',{exact:true}).fill('7.8954007')
  await page.getByLabel('Verified HydroRIVERS reach ID').fill('20446064')
  await page.locator('.investigation-form').getByLabel('Date',{exact:true}).fill('2014-06-25')
  await page.getByLabel('Replicate 1').selectOption('Positive')
  await page.getByRole('button',{name:'Add species or sampling event'}).click()
  await page.getByLabel('Additional target species 1').fill('Salmo trutta')
  await page.getByLabel('Additional sampling date 1').fill('2014-06-26')
  await page.getByLabel('Additional replicate results 1').fill('Negative, Negative')
  await page.getByLabel('Additional observation source 1').fill('Synthetic trout assay')
  await page.getByRole('button',{name:'Create investigation',exact:true}).click()
  await page.waitForURL(/\/investigations\/[0-9a-f-]+$/)
  const caseId=page.url().split('/').at(-1)
  await page.getByRole('button',{name:'Load frozen Wigger reference'}).click()
  await page.getByRole('button',{name:'Evaluate sampling decision'}).click()
  await expect(page.locator('.workspace-heading')).toContainText('TIE')
  const contexts=await (await page.request.get(`${api}/cases/${caseId}/detection-contexts`)).json()
  const trout=contexts.find(context=>context.target_taxon==='Salmo trutta')
  await page.getByLabel('Detection context',{exact:true}).selectOption(trout.id)
  await expect(page.locator('.investigation-panel')).toContainText('Selected species: Salmo trutta')
  await expect(page.locator('.workspace-heading')).toContainText('NOT EVALUATED')
  await expect(page.locator('.zone-grid > div')).toHaveCount(0)
  for(const [label,reach] of [['Trout branch 2','20450127'],['Trout branch 3','20451169']]){
    await page.getByLabel('Hypothesis label',{exact:true}).fill(label)
    await page.getByLabel('Root HydroRIVERS reach ID',{exact:true}).fill(reach)
    await page.getByLabel('Hypothesis reach IDs',{exact:true}).fill(reach)
    await page.getByRole('button',{name:'Register hypothesis',exact:true}).click()
    const zone=page.locator('.zone-grid > div').filter({hasText:label})
    await expect(zone).toContainText('NOT VERIFIED')
    await zone.getByRole('button',{name:'Review directed network relationship'}).click()
    await expect(zone).toContainText('Network validation: MATCHED')
    await expect(zone).toContainText('Hypothesis state: UNKNOWN')
  }
  await page.getByRole('button',{name:/Next Steps/}).click()
  await page.getByRole('button',{name:'Run reinvestigation'}).click()
  await expect(page.getByRole('heading',{name:'Decision trace'})).toBeVisible()
  const troutDecision=await (await page.request.get(`${api}/cases/${caseId}/sampling-decision?detection_context_id=${trout.id}`)).json()
  expect(troutDecision.candidate_scope).toBe('GENERATED_REPRESENTATIVES')
  expect(troutDecision.candidate_snapshot.candidates.filter(c=>troutDecision.recommended_site_ids.includes(c.site_id)).map(c=>c.pair_separation_score)).toEqual([1,1])
  const primaryDecision=await (await page.request.get(`${api}/cases/${caseId}/sampling-decision`)).json()
  expect(primaryDecision.candidate_snapshot.candidates.filter(c=>primaryDecision.recommended_site_ids.includes(c.site_id)).map(c=>c.pair_separation_score)).toEqual([2,2,2])
  await page.goto('/reports')
  await page.getByLabel('Scientific report').selectOption(caseId)
  await page.getByLabel('Report detection context').selectOption(trout.id)
  await expect(page.locator('#summary')).toContainText('Salmo trutta')
  await expect(page.locator('#detection')).toContainText('2014-06-26')
  await expect(page.locator('#evidence')).toContainText('Synthetic trout assay')
  await expect(page.locator('#context')).not.toContainText('10.3390/pathogens9010016')
  await expect(page.locator('#evidence')).not.toContainText('frontend investigation form')
  await page.emulateMedia({media:'print'})
  const pdf=path.resolve('../browser_artifacts/MULTISPECIES_TROUT_REPORT.pdf')
  await page.pdf({path:pdf,format:'A4',printBackground:true})
  const printed=execFileSync('pdftotext',[pdf,'-'],{encoding:'utf8'}).replace(/\s+/g,' ')
  expect(printed).toContain('Salmo trutta');expect(printed).toContain('Synthetic trout assay')
  expect(printed).not.toContain('10.3390/pathogens9010016')
  await page.emulateMedia({media:'screen'})
  await page.goto(`/investigations/${caseId}`)
  const manager=page.locator('details').filter({hasText:'Add species or sampling context'}).first()
  await manager.locator('summary').click()
  await manager.getByLabel('Target species',{exact:true}).fill('Salmo trutta')
  await manager.getByLabel('Site label',{exact:true}).fill('Reviewed upstream detection')
  await manager.getByLabel('WGS84 latitude').fill('47.1729166666')
  await manager.getByLabel('WGS84 longitude').fill('7.99375')
  const canvas=manager.locator('.maplibregl-canvas')
  await expect(canvas).toBeVisible()
  await canvas.click({position:{x:80,y:80}})
  await expect(manager.getByLabel('WGS84 latitude')).not.toHaveValue('47.1729166666')
  await manager.getByLabel('WGS84 latitude').fill('47.1729166666')
  await manager.getByLabel('WGS84 longitude').fill('7.99375')
  await manager.getByRole('button',{name:'Match coordinates'}).click()
  await expect(manager).toContainText('Geographic match: CLOSE')
  await manager.getByRole('button',{name:'Confirm reviewed match'}).click()
  await manager.getByLabel('Sampling date',{exact:true}).fill('2014-06-27')
  await manager.getByLabel('Replicate results (comma separated)').fill('Positive')
  await manager.getByLabel('Observation source',{exact:true}).fill('Synthetic upstream assay')
  await manager.getByRole('button',{name:'Register detection context',exact:true}).click()
  await expect(page.locator('.investigation-panel')).toContainText('Site: Reviewed upstream detection')
  await expect(page.locator('.investigation-panel')).toContainText('2014-06-27')
  await expect(page.locator('.workspace-heading')).toContainText('NOT EVALUATED')
  await page.goto('/sites')
  await page.getByLabel('Site investigation').selectOption(caseId)
  await expect(page.locator('.site-cards')).toContainText('Reviewed upstream detection')
})
