import { ArrowRight, ClipboardCheck, Droplets, GitBranch, Microscope, Search, Waves } from 'lucide-react'
import { Link } from 'react-router-dom'
import ScientificMap from '../components/ScientificMap'
import useRemoteData from '../hooks/useRemoteData'
import { demoApi } from '../services/api'

export default function Home(){const mapRemote=useRemoteData(demoApi.map,[]);return <div className="public-home"><header className="public-nav"><Link to="/" className="fresh-brand"><Waves size={18}/> FreshWater</Link><nav><a href="#workflow">How it works</a><a href="#science">Scientific approach</a><a href="#demo">Wigger demo</a><a href="#about">About</a></nav><Link className="button primary" to="/investigations/new">Start investigation</Link></header>
  <section className="hero"><div><span className="eyebrow">Freshwater research & decision support</span><h1>From uncertain DNA detections to clearer freshwater decisions.</h1><p>Investigate freshwater eDNA observations, explore plausible upstream sources, evaluate competing explanations, and identify informative follow-up sampling locations.</p><div className="button-row"><Link className="button primary" to="/investigations/new">Start investigation</Link><Link className="button" to="/investigations/demo">Explore Wigger demo</Link></div></div><MapPreview title="Wigger River" mapData={mapRemote.data}/></section>
  <section id="workflow" className="public-section"><h2>From observation to investigation.</h2><p>A structured workflow that turns raw eDNA detections into testable hypotheses about where species are coming from.</p><div className="workflow-cards">{[[Microscope,'Assess Evidence','Examine observations, replicate results, and uncertainties.'],[GitBranch,'Trace Possible Sources','Use verified river-network connectivity to identify plausible zones.'],[Search,'Compare Explanations','Investigate competing source hypotheses using available evidence.'],[ClipboardCheck,'Plan Next Sampling','Evaluate sampling locations that can reduce uncertainty.']].map(([Icon,t,d])=><div key={t}><Icon/><h3>{t}</h3><p>{d}</p></div>)}</div></section>
  <section id="demo" className="public-section tinted"><h2>See the complete river investigation.</h2><p>The map below uses the validated Wigger preflight geometry supplied by the scientific backend.</p><MapPreview title="Scientific map preview" large mapData={mapRemote.data}/><Link className="button primary" to="/investigations/demo">Explore demo</Link></section>
  <section id="science" className="public-section"><h2>Better evidence. More informed monitoring.</h2><div className="benefits">{[['Understand uncertainty','See what was detected and what remains plausible.'],['Investigate possible sources','Follow river-network connections without overstating ecological certainty.'],['Improve field decisions','Choose follow-up locations under a transparent decision criterion.']].map(([t,d])=><div key={t}><i></i><h3>{t}</h3><p>{d}</p></div>)}</div></section>
  <section id="about" className="context-band"><div><h2>Connecting freshwater monitoring with ecosystem health.</h2><p>Targeted monitoring can support biodiversity conservation and environmental decisions when evidence and context remain clearly separated.</p></div><div className="river-visual"><Droplets size={52}/><span>Environmental imagery not bundled</span></div></section>
  <section className="final-cta"><h2>Make your next freshwater investigation more informative.</h2><p>Explore uncertain observations, investigate plausible sources, and plan your next field investigation.</p><div className="button-row"><Link className="button primary" to="/investigations/new">Start investigation</Link><Link className="button" to="/investigations/demo">Explore Wigger demo</Link></div></section>
  <footer className="public-footer"><div><strong><Waves size={16}/> FreshWater</strong><p>A research-grade tool for investigating eDNA observations in freshwater systems.</p></div><div><strong>Navigation</strong><Link to="/dashboard">Dashboard</Link><Link to="/investigations">Investigations</Link><Link to="/sites">Sites</Link></div><small>Scientific data attribution is provided within the platform.</small></footer>
  </div>}

function MapPreview({title,large=false,mapData}){return <div className={`home-map ${large?'large':''}`}><ScientificMap compact title={title} mapData={mapData}/></div>}
