import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import ScientificMap from '../components/ScientificMap'
import { Accordion, DataState, StatusBadge } from '../components/UI'
import useRemoteData from '../hooks/useRemoteData'
import { contextApi, demoApi, followUpApi, investigationApi, loadCaseBundle, samplingApi } from '../services/api'

const colors={A:'#F97316',B:'#2563EB',C:'#16A34A',D:'#9333EA'}

export default function InvestigationWorkspace() {
  const {caseId}=useParams(), navigate=useNavigate(), demoStarted=useRef(false)
  const [open,setOpen]=useState({evidence:true,sources:true,decision:true,next:false}), [action,setAction]=useState({busy:false,error:''})
  useEffect(()=>{if(caseId==='demo'&&!demoStarted.current){demoStarted.current=true;demoApi.loadWigger().then(result=>navigate(`/investigations/${result.case_id}`,{replace:true})).catch(error=>setAction({busy:false,error:error.message}))}},[caseId,navigate])
  const remote=useRemoteData(()=>caseId==='demo'?Promise.resolve(null):loadCaseBundle(caseId),[caseId]), mapRemote=useRemoteData(demoApi.map,[])
  if(caseId==='demo'||remote.status==='LOADING')return <DataState status="LOADING" title="Loading scientific investigation" message="Retrieving persisted case data and validated map layers."/>
  if(remote.status==='ERROR'||!remote.data)return <DataState status="ERROR" title="Investigation unavailable" message={action.error||remote.error?.message}/>
  const bundle=remote.data, caseData=bundle.case, historical=caseData?.metadata?.historical_observation, isWigger=Boolean(historical)
  const sites=(bundle.sites||[]).map(s=>({...s,name:s.label,type:s.site_type,color:colors[s.label?.replace('Site ','')]||'#64748b'})), assessments=bundle.assessments||[]
  const latestRun=bundle.runs?.at(-1), decision=bundle.decision||latestRun?.sampling_decision||(bundle.generated?{status:bundle.generated.decision_status,rationale:bundle.generated.decision_reason}:null)
  const toggle=k=>setOpen({...open,[k]:!open[k]})
  async function act(operation){setAction({busy:true,error:''});try{await operation();await remote.reload();setAction({busy:false,error:''})}catch(error){setAction({busy:false,error:error.message})}}
  return <div className="workspace"><div className="workspace-map"><ScientificMap compact sites={isWigger?(mapRemote.data?.sites||[]).map(s=>({...s,name:`Site ${s.label}`,color:colors[s.label]})):sites} mapData={isWigger?mapRemote.data:null} title={caseData?.metadata?.name||'Scientific investigation'}/></div><aside className="investigation-panel"><div className="workspace-heading"><div><h1>Scientific investigation</h1><p>{caseData?.metadata?.name||`Case ${caseId.slice(0,8)}`}</p></div><StatusBadge value={decision?.status||'NOT_EVALUATED'}/></div>
    <div className="workspace-summary"><span><small>Target species</small><strong><i>{caseData.target_taxon}</i></strong></span><span><small>Detection site</small><strong>{sites.find(s=>s.site_type==='DETECTION_SITE')?.label||'Site A'}</strong></span><span><small>Evidence status</small><strong>{assessments.length?'Assessed':'Not evaluated'}</strong></span></div>
    <Accordion title="Detection Evidence" open={open.evidence} onToggle={()=>toggle('evidence')}><div className="label-row"><StatusBadge value={bundle.evidence?.length?'READY':'UNKNOWN'}/><span>{bundle.evidence?.length||0} evidence item(s)</span></div><div className="detail-grid"><div><small>Species</small><strong>{caseData.target_taxon}</strong></div><div><small>Station</small><strong>{historical?.station||sites.find(s=>s.site_type==='DETECTION_SITE')?.label||'Unavailable'}</strong></div><div><small>Observation index</small><strong>{historical?.observation_index??'Unavailable'}</strong></div><div><small>Sampling date</small><strong>{caseData.observation_date}</strong></div><div><small>Historical state</small><strong>{historical?.state||'Unavailable'}</strong></div><div><small>Concentration</small><strong>{historical?.concentration_mol_l!=null?`${historical.concentration_mol_l} mol/L`:'Unavailable'}</strong></div></div>{bundle.context?.map(c=><div className="notice" key={c.provider}><strong>{c.provider}: {c.status}</strong><p>{c.limitations?.join(' ')}</p></div>)}<button className="button" disabled={action.busy} onClick={()=>act(()=>contextApi.collect(caseId,{radius_m:5000,weather_window_days:0}))}>Collect available context</button></Accordion>
    <Accordion title="Possible Sources" open={open.sources} onToggle={()=>toggle('sources')}><div className="zone-grid">{(bundle.zones||[]).map(zone=>{const result=assessments.find(a=>a.zone_id===zone.id);return <div key={zone.id}><strong>{zone.label}</strong><small>Root reach {zone.root_hyriv_id}</small>{result?<><p>Supports {result.summary.supports}; contradicts {result.summary.contradicts}; neutral {result.summary.neutral}; unknown {result.summary.unknown}</p>{result.assessments.map(a=><p key={a.evidence_id}><b>{a.compatibility}</b> · {a.rule_id||'No applicable rule'} · {a.reason}</p>)}</>:<p>Evidence assessment unavailable.</p>}</div>})}</div>{!bundle.zones?.length&&<p>No candidate zones are registered.</p>}</Accordion>
    <Accordion title="Sampling Decision" open={open.decision} onToggle={()=>toggle('decision')} trailing={<StatusBadge value={decision?.status||'NOT_EVALUATED'}/>}><p>{decision?.rationale||'No scientific decision has been calculated.'}</p>{bundle.generated?.candidates?.length>0&&<SimpleCandidates candidates={bundle.generated.candidates}/>} {bundle.trace&&<Trace trace={bundle.trace}/>}<button className="button primary" disabled={action.busy||!bundle.zones?.length} onClick={()=>act(()=>samplingApi.decide(caseId))}>Evaluate sampling decision</button></Accordion>
    <Accordion title="Next Steps" open={open.next} onToggle={()=>toggle('next')}><p>Register a real follow-up sample with assay, controls, replicate counts, collector source, and provenance.</p><FollowUpForm sites={sites} candidates={bundle.generated?.candidates||[]} busy={action.busy} onSubmit={payload=>act(()=>followUpApi.create(caseId,payload))}/><button className="button" disabled={action.busy||!bundle.zones?.length} onClick={()=>act(()=>investigationApi.reinvestigate(caseId,{}))}>Run reinvestigation</button>{latestRun&&<p>Latest run: {latestRun.status} · {latestRun.investigation_run_id}</p>}</Accordion>
    {action.error&&<div className="error-banner">{action.error}</div>}
  </aside></div>
}

function SimpleCandidates({candidates}){return <div className="table-scroll"><table><thead><tr><th>Reach</th><th>Signature</th><th>Distinguished pairs</th><th>Pair score</th><th>Distance</th></tr></thead><tbody>{candidates.map(c=><tr key={c.hyriv_id}><td>{c.hyriv_id}</td><td>[{c.signature.join(', ')}]</td><td>{c.distinguished_hypothesis_pairs?.map(pair=>pair.join(' vs ')).join('; ')||'None'}</td><td>{c.pair_separation_score}</td><td>{c.network_distance_km.toFixed(3)} km</td></tr>)}</tbody></table></div>}
function Trace({trace}){return <div className="trace"><h3>Decision trace</h3><p><b>Rules:</b> {trace.rules_applied?.join(', ')||'None'}</p><p><b>Assumptions:</b> {trace.assumptions?.join(' ')}</p><p><b>Limitations:</b> {trace.limitations?.join(' ')}</p></div>}
function FollowUpForm({sites,candidates,busy,onSubmit}){const [form,setForm]=useState({reference:'',sampled_at:'',replicate_count:1,positive_replicates:0,assay:'',controls_status:'',collector_source:''});const options=[...sites.map(s=>({value:`site:${s.id}`,label:s.label,hyriv_id:s.hyriv_id})),...candidates.map(c=>({value:`candidate:${c.hyriv_id}`,label:`Candidate reach ${c.hyriv_id}`,hyriv_id:c.hyriv_id}))];function submit(e){e.preventDefault();const target=options.find(o=>o.value===form.reference);if(!target)return;const isSite=form.reference.startsWith('site:');onSubmit({sampling_site_id:isSite?form.reference.slice(5):null,candidate_reference:isSite?null:`HYRIV_ID:${target.hyriv_id}`,hyriv_id:target.hyriv_id,sampled_at:new Date(form.sampled_at).toISOString(),replicate_count:+form.replicate_count,positive_replicates:+form.positive_replicates,concentration:null,concentration_unit:null,assay:form.assay,controls_status:form.controls_status,collector_source:form.collector_source,provenance:{entry_method:'frontend'},notes:null})}return <form className="follow-up-form" onSubmit={submit}><select required value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}><option value="">Select sampled site</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><input required type="datetime-local" value={form.sampled_at} onChange={e=>setForm({...form,sampled_at:e.target.value})}/><div className="form-row"><input required min="1" type="number" aria-label="Replicate count" value={form.replicate_count} onChange={e=>setForm({...form,replicate_count:e.target.value})}/><input required min="0" type="number" aria-label="Positive replicates" value={form.positive_replicates} onChange={e=>setForm({...form,positive_replicates:e.target.value})}/></div><input required placeholder="Assay" value={form.assay} onChange={e=>setForm({...form,assay:e.target.value})}/><input required placeholder="Controls status" value={form.controls_status} onChange={e=>setForm({...form,controls_status:e.target.value})}/><input required placeholder="Collector source" value={form.collector_source} onChange={e=>setForm({...form,collector_source:e.target.value})}/><button className="button" disabled={busy||!options.length}>Register follow-up sample</button></form>}
