import { Download } from 'lucide-react'
import { userFacingText } from '../services/presentation'
import { reportSections } from '../data/appData'
import { StatusBadge, NetworkDistance } from '../components/UI'
import ScientificMap from '../components/ScientificMap'
import BundleErrors from '../components/BundleErrors'
import TieMonitoringPlan from '../components/TieMonitoringPlan'
import { useEffect, useMemo, useState, useRef } from 'react'
import AIReportPanel from '../components/AIReportPanel'
import useRemoteData from '../hooks/useRemoteData'
import { casesApi, detectionApi, loadReportBundle } from '../services/api'

const Section=({id,title,children})=><section id={id} className="report-section"><h2>{title}</h2>{children}</section>

export default function Reports(){
  const aiPanel = useRef(null)
  async function exportReport() {
    const panel = aiPanel.current
    await panel?.refreshForPrint()
    await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))
    if (panel !== aiPanel.current) return
    window.print()
  }
  const casesRemote=useRemoteData(casesApi.list,[]), cases=useMemo(()=>casesRemote.data?.cases||[],[casesRemote.data]), [selected,setSelected]=useState('')
  useEffect(()=>{if(!selected&&cases.length)setSelected(cases[0].id)},[cases,selected])
  const [contextId,setContextId]=useState('')
  const contextRemote=useRemoteData(()=>selected?detectionApi.contexts(selected):Promise.resolve([]),[selected])
  const contexts=contextRemote.data||[]
  const selectedContext=contexts.find(context=>context.id===contextId)
  const scope=selectedContext?.id||''
  const bundleRemote=useRemoteData(()=>selected?loadReportBundle(selected,scope):Promise.resolve(null),[selected,scope]), bundle=bundleRemote.data?.case?.id===selected&&bundleRemote.data?.detectionContextId===(scope||null)?bundleRemote.data:{}, caseData=bundle.case
  const decision=bundle.decision, historical=caseData?.metadata?.historical_observation
  const evidenceById=Object.fromEntries((bundle.evidence||[]).map(item=>[item.id,item])), assessmentRows=(bundle.assessments||[]).flatMap(zone=>zone.assessments.map(item=>{const evidence=evidenceById[item.evidence_id]||{};return [zone.zone_label,evidence.evidence_type||'Unavailable',displaySource(evidence.source),item.rule_id||'No applicable rule',item.compatibility,item.reason,evidence.quality||'UNASSESSED']}))
  const detectionSite=(bundle.sites||[]).find(site=>site.id===caseData?.detection_site_id), networkFeatures=bundle.map?.river_network?.features||[], networkLength=networkFeatures.reduce((total,feature)=>total+Number(feature.properties?.LENGTH_KM||0),0)
  const eligible=(decision?.recommended_site_ids||[]).map(id=>(bundle.sites||[]).find(site=>site.id===id)?.label||bundle.comparison?.candidates?.find(candidate=>candidate.site_id===id)?.label||(decision.candidate_scope==='GENERATED_REPRESENTATIVES'?`Generated reach ${bundle.comparison?.candidates?.find(candidate=>candidate.site_id===id)?.hyriv_id??'unavailable'}`:'Sampling site label unavailable'))
  const historyCompatibility=bundle.investigationRun?.compatibility||decision?.compatibility
  const oneHealthRows=(bundle.oneHealth?.pathways||[]).map(pathway=>[pathway.monitoring_finding?.status||'UNKNOWN',pathway.monitoring_finding?.statement||'Unavailable',pathway.possible_monitoring_action?.statement||'Unavailable'])
  const missing=[...(historyCompatibility?.limitations||[]),...(!['MATCHED','VERIFIED'].includes(detectionSite?.validation_status)?['Detection location validation']:[]),...(bundle.zones?.some(zone=>zone.validation_status==='NOT_VERIFIED')?['Source hypothesis validation']:[]),...Object.keys(bundle.errors||{}).map(key=>`${key} unavailable`),...(!bundle.evidence?.length?['Observed evidence']:[]),...(!bundle.zones?.length?['Source hypotheses']:[]),...(!bundle.comparison?.candidates?.length?['Candidate comparison']:[]),...(!decision?['Persisted decision']:[]),...(!bundle.trace?['Decision trace']:[])]
  const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})
  return <div className="reports-layout"><aside className="report-toc"><h1>Reports</h1><p>Draft investigation records and exportable methods.</p><strong>In this report</strong>{reportSections.map(([id,title])=><button key={id} onClick={()=>scroll(id)}>{title}</button>)}</aside><div className="report-column"><div className="report-controls"><label>Scientific report<select value={selected} onChange={e=>{setSelected(e.target.value);setContextId('')}}><option value="">Select investigation</option>{cases.map(c=><option key={c.id} value={c.id}>{c.metadata?.name||c.target_taxon}</option>)}</select></label><label>Report detection context<select aria-label="Report detection context" value={scope} onChange={event=>setContextId(event.target.value)}><option value="">Primary detection</option>{contexts.filter(context=>!context.is_primary).map(context=><option key={context.id} value={context.id}>{context.target_taxon} · {context.site_label} · {context.sampled_on} {context.event_label}</option>)}</select></label><StatusBadge value={decision?.status||'NOT_EVALUATED'}/><button className="button primary" disabled={!caseData||bundleRemote.status==='LOADING'||Boolean(bundleRemote.error)||Boolean(Object.keys(bundle.errors||{}).length)} onClick={exportReport}><Download size={15}/> Export PDF</button></div><BundleErrors errors={{...bundle.errors,...(casesRemote.error?{cases:casesRemote.error}:{}),...(bundleRemote.error?{report:bundleRemote.error}:{})}} onRetry={()=>{casesRemote.reload();bundleRemote.reload()}}/>{bundleRemote.status==='LOADING'||!caseData?<div className="report-document"><p>{bundleRemote.status==='LOADING'?'Loading report data…':'No investigation selected or backend unavailable.'}</p></div>:<article className="report-document"><header><div><h1>{caseData.metadata?.name||'Unnamed investigation'}</h1><p>Draft investigation record for an uncertain freshwater eDNA detection.</p></div><StatusBadge value={decision?.status||'NOT_EVALUATED'}/></header>
    <div className="report-meta"><span><small>Report status</small><strong>Draft</strong></span><span><small>Observation date</small><strong>{caseData.observation_date}</strong></span><span><small>Prepared for</small><strong>Scientific review</strong></span><span><small>Scientific decision</small><strong>{decision?.status||'NOT_EVALUATED'}</strong></span></div>
    <Section id="summary" title="Investigation Summary"><p>Report scope: {caseData.target_taxon} · {detectionSite?.label||'Site unavailable'} · {caseData.observation_date}. Each detection context has its own observations, decisions and history.</p>{missing.length>0&&<div className="warning-box">Draft — missing or unavailable: {missing.join('; ')}.</div>}<p>A structured record for evaluating an uncertain eDNA detection and identifying a defensible follow-up action.</p></Section>
    <Section id="detection" title="Original eDNA Detection"><SimpleTable heads={['Field','Value']} rows={[['Species',caseData.target_taxon],['Station',historical?.station||detectionSite?.label||'Unavailable'],['Observation index',historical?.observation_index??'Unavailable'],['Detection site reach',detectionSite?.hyriv_id??'Unavailable'],['Detection validation',detectionSite?.validation_status||'Unavailable'],['Validation reason',detectionSite?.metadata?.validation_reason||'See persisted network provenance'],['Detection provenance',detectionSite?.metadata?.network_source?displaySource(detectionSite.metadata.network_source):'Unavailable'],['Coordinates',detectionSite?`${detectionSite.latitude}, ${detectionSite.longitude}`:'Unavailable'],['Sampling date',caseData.observation_date],['Laboratory or assay metadata',caseData.metadata?.additional_metadata||'Unavailable'],['Historical state',historical?.state||'Unavailable'],['Concentration',historical?.concentration_mol_l!=null?`${historical.concentration_mol_l} mol/L`:'Unavailable'],['Observation trust',bundle.oneHealth?.observation_provenance||'Unavailable'],['Replicate and assay metadata',(bundle.evidence||[]).some(item=>Array.isArray(item.value?.replicate_results))?'See persisted replicate observations below':'Unavailable in the persisted evidence']]}/>{(bundle.evidence||[]).some(item=>Array.isArray(item.value?.replicate_results))&&<SimpleTable heads={['Observation source','Replicate','Recorded result','Assay metadata','Provenance']} rows={bundle.evidence.flatMap(item=>(Array.isArray(item.value?.replicate_results)?item.value.replicate_results:[]).map((result,index)=>[item.provenance?.entry_method==='manual'?'User-entered observation':displaySource(item.source),index+1,result,item.value.assay_metadata?typeof item.value.assay_metadata==='string'?item.value.assay_metadata:displayRecord(item.value.assay_metadata):'Unavailable',displayRecord(item.provenance)]))}/>}</Section>
    <Section id="evidence" title="Evidence Assessment">{Boolean(bundle.evidence?.length)&&<SimpleTable heads={['Evidence type','Classification','Source','Observed','Quality','Recorded value','Provenance']} rows={bundle.evidence.map(item=>[item.evidence_type,item.id===bundle.oneHealth?.reference_evidence_id?'Verified source observation':item.evidence_type.startsWith('context_')?'Unassessed environmental context':item.evidence_type==='sampling_field_plan'?'Researcher field-planning record':item.evidence_type==='directed_hydrological_connectivity'?'Graph claim; see assessment':'User-reported observation; interpretation unassessed',displaySource(item.source),item.observed_at?new Date(item.observed_at).toLocaleString():'Unavailable',item.quality||'UNASSESSED',displayRecord(item.value),displayRecord(item.provenance)])}/>} {assessmentRows.length?<><SimpleTable heads={['Zone','Evidence','Source','Rule','Result','Explanation','Quality']} rows={assessmentRows}/>{assessmentRows.every(row=>row[4]==='UNKNOWN')&&<div className="warning-box">Evidence was evaluated, but the available validated rules were insufficient to determine compatibility.</div>}</>:<div className="warning-box">{!bundle.evidence?.length?'Evidence records are missing; no assessment can be performed.':!bundle.zones?.length?'Source hypotheses are missing; evidence cannot yet be compared.':'No persisted assessment result is available.'}</div>}</Section>
    <Section id="hydrology" title="Hydrological Investigation"><p>{bundle.zones?.length?`${bundle.zones.length} candidate zones and ${bundle.sites?.length||0} sites are registered. Validation is shown for each hypothesis; registration alone does not verify user data. The validated map contains ${networkFeatures.length} reaches totaling ${networkLength.toFixed(2)} km.`:'No candidate zones are registered.'}</p><p>Directed connectivity establishes a possible mapped transport pathway. It does not confirm the biological source.</p></Section>
    <Section id="map" title="Investigation Map">{bundle.map?.available?<ScientificMap compact mapData={bundle.map} error={bundle.errors?.map} onRetry={bundleRemote.reload} title={caseData.metadata?.name||'Investigation geography'}/>:<div className="report-map"><strong>Verified spatial data unavailable</strong><small>{bundle.map?.unavailable_reason||'No verified geometry is linked to this investigation.'}</small></div>}</Section>
    <Section id="sources" title="Competing Source Explanations">{bundle.zones?.length?<SimpleTable heads={['Zone','Root reach','Reach count','Validation','Provenance']} rows={bundle.zones.map(z=>[z.label,z.root_hyriv_id,z.reach_ids.length,z.validation_status,displayRecord(z.metadata)])}/>:<div className="warning-box">No source hypotheses are registered.</div>}</Section>
    <Section id="candidates" title="Candidate Sampling Comparison">{decision&&<p>Candidate scope: {decision.candidate_scope}.</p>}{bundle.comparison?.candidates?.length?<><p>{decision?.candidate_scope==='REGISTERED_SITES'?'The comparison uses registered sampling sites evaluated for this decision.':'The generated reaches are one representative per useful, validated upstream reachability signature. A zero-separation signature is excluded; the nearest reach to the detection site represents each remaining signature. This distance chooses a representative within a class and is not a biological ranking. Generated reaches are not automatically registered field sites.'}</p><p>Network distance follows directed river reaches in kilometers. Snap distance is the coordinate-to-network offset in meters; it is a different measurement.</p><SimpleTable heads={['Reach','Signature','Distinguished pairs','Pair separation','Network distance to detection','Validation']} rows={bundle.comparison.candidates.map(c=>[c.hyriv_id,Array.isArray(c.signature)?`[${c.signature.join(', ')}]`:'Unavailable',c.distinguished_hypothesis_pairs?.map(pair=>pair.join(' vs ')).join('; ')||'None',c.pair_separation_score??'Unavailable',<NetworkDistance candidate={c}/>,c.validation_status||'See decision trace'])}/><p>Eligibility for a registered-site field recommendation also requires a scientifically valid registered site and validated zone network state. The score assumes ideal binary outcomes and does not estimate detection probability.</p></>:<div className="warning-box">Candidate comparison is unavailable. Register source hypotheses before generating candidates.</div>}</Section>
    <Section id="decision" title="Sampling Decision and Scientific Reasoning"><div className="warning-box"><strong>{decision?.status||'NOT_EVALUATED'}</strong><p>{decision?.rationale||'No persisted scientific decision exists. Register hypotheses and candidate sites, then evaluate the sampling decision.'}</p></div>{bundle.trace&&<><p>Rules applied: {bundle.trace.rules_applied?.join(', ')||'Unavailable'}</p><p>Evidence used: {bundle.trace.evidence_used?.map(id=>evidenceById[id]?.evidence_type||'Historical evidence record').join(', ')||'None recorded'}</p>{bundle.trace.hydrology_checks?.length>0&&<SimpleTable heads={['Hydrology check']} rows={bundle.trace.hydrology_checks.map(check=>[displayRecord(check)])}/>}<p>Scientific rule versions: {Object.entries(bundle.trace.rule_versions||{}).map(([id,version])=>`${id}: ${version}`).join('; ')||'Unavailable in the historical trace'}</p><p>Trace recorded: {bundle.trace.created_at||'Unavailable'}</p></>}</Section>
    <Section id="monitoring" title="Actionable TIE Monitoring Plan"><TieMonitoringPlan decision={decision} comparison={bundle.comparison} sites={bundle.sites||[]} labels={(bundle.zones||[]).map(zone=>zone.label)} evidence={bundle.evidence||[]}/>{decision?.status!=='TIE'&&<p>No TIE alternatives are stored for this decision.</p>}</Section>
    <Section id="history" title="Versioned Reinvestigation History"><RunHistory history={bundle.history||[]} unavailable={Boolean(bundle.errors?.runs)}/></Section>
    <Section id="followup" title="Follow-up Sampling"><p>{eligible.length?`Eligible sites under the persisted decision: ${eligible.join(', ')}.`:'No persisted follow-up recommendation is available.'} A negative sample does not prove absence and a positive sample does not by itself prove the exact source.</p>{bundle.followUps?.length?<SimpleTable heads={['Sampled','Reach','Positive / total','Assay','Controls','Collector']} rows={bundle.followUps.map(sample=>[new Date(sample.sampled_at).toLocaleString(),sample.hyriv_id,`${sample.positive_replicates} / ${sample.replicate_count}`,sample.assay,sample.controls_status,sample.collector_source])}/>:<p>{bundle.errors?.followUps?'Follow-up samples unavailable.':'No follow-up samples have been registered.'}</p>}</Section>
    <Section id="context" title="Environmental and One Health Context"><p>Context does not independently establish source presence, pollution, disease, or human-health risk.</p>{bundle.context?.length?<SimpleTable heads={['Provider','Status','Diagnostics','Limitations','Collected','Compatibility']} rows={bundle.context.map(c=>[c.provider,c.status,c.error||'No provider error recorded',(c.limitations||[]).join(' '),c.collected_at||'Historical collection time unavailable',c.compatibility])}/>:<p>{bundle.errors?.context?'Environmental context unavailable.':'No environmental context records were collected for this report.'}</p>}{oneHealthRows.length>0&&<SimpleTable heads={['Status','Supported monitoring finding','Possible monitoring action']} rows={oneHealthRows}/>}<OneHealthDetails assessment={bundle.oneHealth}/><p>UNAVAILABLE or ERROR means context could not be established. It is not evidence that an environmental condition is absent. An empty successful response reports no returned records within provider coverage.</p></Section>
    <AIReportPanel key={`${selected}:${scope}`} ref={aiPanel} caseId={selected} contextId={scope}/>
    <Section id="next" title="Next Steps"><p>{!bundle.evidence?.length?'Record observed evidence and its provenance. ':''}{!bundle.zones?.length?'Register scientifically supported source hypotheses. ':''}{!bundle.generated?.candidates?.length?'Generate a candidate comparison after hypotheses are available. ':''}{!decision?'Evaluate and persist a sampling decision when prerequisites are complete. ':''}{decision&&!bundle.followUps?.length?'Register actual follow-up samples when field results are available.':''}</p></Section>
    <Section id="data" title="Data Sources"><SimpleTable heads={['Source','Availability']} rows={[['Backend investigation records','Loaded'],['Verified HydroRIVERS spatial data',bundle.map?.available?displaySource(bundle.map.provenance?.river_network)||'Loaded with EPSG:4326 provenance':'Unavailable'],['Observation provenance',historical?.provenance?.edna_source?displaySource(historical.provenance.edna_source):(bundle.evidence?.length?'Stored with evidence records':'Unavailable')],['Scientific rules',(bundle.trace?.rules_applied||[]).join(', ')||'No persisted decision trace']]}/></Section>
    <Section id="assumptions" title="Assumptions"><p>{userFacingText(bundle.trace?.assumptions?.join(' '))||'No decision-trace assumptions are available.'}</p></Section>
    <Section id="limitations" title="Limitations"><p>{userFacingText(bundle.trace?.limitations?.join(' '))||'No decision-trace limitations are available. No confidence score is inferred.'}</p></Section>
  </article>}</div></div>
}

function SimpleTable({heads,rows}){return <div className="table-scroll"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function displaySource(source){if(!source)return 'Unavailable';const marker='/data_preflight/';const index=source.indexOf(marker);return index>=0?source.slice(index+1):source}

function OneHealthDetails({assessment}) {
  return <div><p>Observation provenance: {assessment?.observation_provenance||'Unavailable'}.</p>
    {(assessment?.limitations||[]).map(note=><p key={note}>{note}</p>)}
    {(assessment?.pathways||[]).map(pathway=><div key={pathway.pathway_id}>
      <h3>Documented relationships and local outcomes</h3>
      <SimpleTable heads={['Claim','Classification','Statement','Evidence references']} rows={[
        ['ecological_relevance','animal_health_relevance','community_management_relevance','possible_monitoring_action','parasite_presence','fish_disease_status','human_health_impact']
          .map(key=>[key.replaceAll('_',' '),pathway[key]?.status||'UNKNOWN',pathway[key]?.statement||'Unavailable',(pathway[key]?.evidence_references||[]).join('; ')])
      ].flat()}/>
      <p>Literature relationships do not establish local parasite presence, fish disease or human-health impact.</p>
      <ul>{(pathway.scientific_sources||[]).map(source=><li key={source.doi}>{source.authors?.join(', ')} ({source.year}). {source.title}. {source.journal}. <a href={`https://doi.org/${source.doi}`}>DOI: {source.doi}</a> — {source.supports}</li>)}</ul>
      <p>Assumptions: {pathway.assumptions?.join(' ')}</p><p>Limitations: {pathway.limitations?.join(' ')}</p>
    </div>)}
  </div>
}

function RunHistory({history,unavailable}) {
  if(unavailable)return <p>Investigation history is unavailable; no conclusion about unchanged results can be drawn.</p>
  if(!history.length)return <p>No reinvestigation runs are stored.</p>
  return history.map((run,index)=><div key={run.investigation_run_id} className="notice"><h3>Run {index+1}</h3>
    <p>Status: {run.status} · Started: {run.started_at} · Completed: {run.completed_at||'Unavailable'} · Previous decision: {run.before?.decision?.status||(run.previous_decision_id?'Historical result unavailable':'None')} · Current decision: {run.after?.decision?.status||'Unavailable'}.</p>
    {run.history_unavailable?<p>Historical result unavailable: {run.history_error}. No unchanged-result conclusion is supported.</p>:<>
      <p>Comparison availability: {run.change_comparison_status||'UNAVAILABLE_HISTORY'}. {userFacingText(run.change_reason)||'Historical change information unavailable.'}</p>
      {(run.compatibility?.limitations||[]).map(note=><p key={note}>{note}</p>)}
      <SimpleTable heads={['Version','Hypotheses','Candidate reaches','Decision']} rows={['before','after'].map(version=>[version,
        run[version]?.hypothesis_states?.map(item=>`${item.zone_label}: ${item.status}`).join('; ')||'Unavailable',
        run[version]?.candidate_representatives?.join(', ')||'Unavailable',run[version]?.decision?.status||'Unavailable'])}/>
    </>}
  </div>)
}

function displayRecord(value){return JSON.stringify(value,(_key,item)=>typeof item==='string'?userFacingText(item):item)}
