import { Download } from 'lucide-react'
import { reportSections } from '../data/appData'
import { StatusBadge } from '../components/UI'
import ScientificMap from '../components/ScientificMap'
import { useEffect, useMemo, useState } from 'react'
import useRemoteData from '../hooks/useRemoteData'
import { casesApi, demoApi, loadCaseBundle } from '../services/api'

const Section=({id,title,children})=><section id={id} className="report-section"><h2>{title}</h2>{children}</section>

export default function Reports(){
  const casesRemote=useRemoteData(casesApi.list,[]), cases=useMemo(()=>casesRemote.data?.cases||[],[casesRemote.data]), [selected,setSelected]=useState('')
  const mapRemote=useRemoteData(demoApi.map,[])
  useEffect(()=>{if(!selected&&cases.length)setSelected(cases[0].id)},[cases,selected])
  const bundleRemote=useRemoteData(()=>selected?loadCaseBundle(selected):Promise.resolve(null),[selected]), bundle=bundleRemote.data||{}, caseData=bundle.case
  const latestRun=bundle.runs?.at(-1), decision=bundle.decision||latestRun?.sampling_decision||(bundle.generated?{status:bundle.generated.decision_status,rationale:bundle.generated.decision_reason}:null), historical=caseData?.metadata?.historical_observation
  const evidenceById=Object.fromEntries((bundle.evidence||[]).map(item=>[item.id,item])), assessmentRows=(bundle.assessments||[]).flatMap(zone=>zone.assessments.map(item=>{const evidence=evidenceById[item.evidence_id]||{};return [zone.zone_label,evidence.evidence_type||'Unavailable',displaySource(evidence.source),item.rule_id||'No applicable rule',item.compatibility,item.reason,evidence.quality||'UNASSESSED']}))
  const detectionSite=(bundle.sites||[]).find(site=>site.id===caseData?.detection_site_id), networkFeatures=mapRemote.data?.river_network?.features||[], networkLength=networkFeatures.reduce((total,feature)=>total+Number(feature.properties?.LENGTH_KM||0),0)
  const eligible=(decision?.recommended_site_ids||[]).map(id=>(bundle.sites||[]).find(site=>site.id===id)?.label).filter(Boolean)
  const oneHealthRows=(bundle.oneHealth?.pathways||[]).map(pathway=>[pathway.monitoring_finding?.status||'UNKNOWN',pathway.monitoring_finding?.statement||'Unavailable',pathway.possible_monitoring_action?.statement||'Unavailable'])
  const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})
  return <div className="reports-layout"><aside className="report-toc"><h1>Reports</h1><p>Research-ready investigation records and exportable methods.</p><strong>In this report</strong>{reportSections.map(([id,title])=><button key={id} onClick={()=>scroll(id)}>{title}</button>)}</aside><div className="report-column"><div className="report-controls"><label>Scientific report<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select investigation</option>{cases.map(c=><option key={c.id} value={c.id}>{c.metadata?.name||c.target_taxon}</option>)}</select></label><StatusBadge value={decision?.status||'NOT_EVALUATED'}/><button className="button primary" disabled={!caseData} onClick={()=>window.print()}><Download size={15}/> Export PDF</button></div>{!caseData?<div className="report-document"><p>{bundleRemote.status==='LOADING'?'Loading report data…':'No investigation selected or backend unavailable.'}</p></div>:<article className="report-document"><header><div><h1>{caseData.metadata?.name||`Investigation ${caseData.id.slice(0,8)}`}</h1><p>Research-ready investigation record for an uncertain freshwater eDNA detection.</p></div><StatusBadge value={decision?.status||'NOT_EVALUATED'}/></header>
    <div className="report-meta"><span><small>Report status</small><strong>Draft</strong></span><span><small>Observation date</small><strong>{caseData.observation_date}</strong></span><span><small>Prepared for</small><strong>Scientific review</strong></span><span><small>Scientific decision</small><strong>{decision?.status||'NOT_EVALUATED'}</strong></span></div>
    <Section id="summary" title="Investigation Summary"><p>A structured record for evaluating an uncertain eDNA detection and identifying a defensible follow-up action.</p></Section>
    <Section id="detection" title="Original eDNA Detection"><SimpleTable heads={['Field','Value']} rows={[['Species',caseData.target_taxon],['Station',historical?.station||detectionSite?.label||'Unavailable'],['Observation index',historical?.observation_index??'Unavailable'],['Detection site reach',detectionSite?.hyriv_id??'Unavailable'],['Coordinates',detectionSite?`${detectionSite.latitude}, ${detectionSite.longitude}`:'Unavailable'],['Sampling date',caseData.observation_date],['Historical state',historical?.state||'Unavailable'],['Concentration',historical?.concentration_mol_l!=null?`${historical.concentration_mol_l} mol/L`:'Unavailable'],['Replicate and assay metadata','Unavailable in the verified H001 record']]}/></Section>
    <Section id="evidence" title="Evidence Assessment">{assessmentRows.length?<SimpleTable heads={['Zone','Evidence','Source','Rule','Result','Explanation','Quality']} rows={assessmentRows}/>:<div className="warning-box">No evidence assessment is available.</div>}</Section>
    <Section id="hydrology" title="Hydrological Investigation"><p>{bundle.zones?.length?`${bundle.zones.length} candidate zones and ${bundle.sites?.length||0} sites are registered with validated reach identifiers. The validated map contains ${networkFeatures.length} reaches totaling ${networkLength.toFixed(2)} km.`:'No candidate zones are registered.'}</p><p>Directed connectivity establishes a possible mapped transport pathway. It does not confirm the biological source.</p></Section>
    <Section id="map" title="Investigation Map">{historical&&mapRemote.data?<ScientificMap compact mapData={mapRemote.data} title="Verified Wigger River network"/>:<div className="report-map"><strong>Verified spatial data unavailable</strong><small>No coordinates or source geometry are represented.</small></div>}</Section>
    <Section id="sources" title="Competing Source Explanations"><SimpleTable heads={['Zone','Root reach','Validation']} rows={(bundle.zones||[]).map(z=>[z.label,z.root_hyriv_id,z.validation_status])}/></Section>
    <Section id="candidates" title="Candidate Sampling Comparison"><SimpleTable heads={['Reach','Signature','Distinguished pairs','Pair separation','Validation']} rows={(bundle.generated?.candidates||[]).map(c=>[c.hyriv_id,`[${c.signature.join(', ')}]`,c.distinguished_hypothesis_pairs?.map(pair=>pair.join(' vs ')).join('; ')||'None',c.pair_separation_score,c.validation_status])}/></Section>
    <Section id="decision" title="Sampling Decision and Scientific Reasoning"><div className="warning-box"><strong>{decision?.status||'NOT EVALUATED'}</strong><p>{decision?.rationale||'No scientific decision has been issued.'}</p></div></Section>
    <Section id="followup" title="Follow-up Sampling"><p>{eligible.length?`Eligible tied sites under the persisted decision: ${eligible.join(', ')}.`:'No unique persisted follow-up recommendation is available.'} Further sampling can test the remaining source hypotheses, but a negative sample does not prove absence and a positive sample does not by itself prove the exact source.</p><p>Field protocol, replicate count, assay, controls, collection time, and provenance must be supplied from the actual sampling design.</p></Section>
    <Section id="context" title="Environmental and One Health Context"><p>Context does not independently establish source presence, pollution, disease, or human-health risk.</p>{bundle.context?.length?<SimpleTable heads={['Provider','Availability','Compatibility']} rows={bundle.context.map(c=>[c.provider,c.status,c.compatibility])}/>:<p>No environmental context records were collected for this report.</p>}{oneHealthRows.length>0&&<SimpleTable heads={['Status','Supported monitoring finding','Possible monitoring action']} rows={oneHealthRows}/>}</Section>
    <Section id="data" title="Data Sources"><SimpleTable heads={['Source','Availability']} rows={[['Backend investigation records','Loaded'],['Verified Wigger preflight spatial data',historical?'Loaded with EPSG:4326 provenance':'Not linked'],['Carraro historical eDNA source',displaySource(historical?.provenance?.edna_source)||'Unavailable'],['Scientific rules',(bundle.trace?.rules_applied||[]).join(', ')||'No persisted decision trace']]}/></Section>
    <Section id="assumptions" title="Assumptions"><p>{bundle.trace?.assumptions?.join(' ')||'No decision-trace assumptions are available.'}</p></Section>
    <Section id="limitations" title="Limitations"><p>{bundle.trace?.limitations?.join(' ')||'No decision-trace limitations are available. No confidence score is inferred.'}</p></Section>
  </article>}</div></div>
}

function SimpleTable({heads,rows}){return <div className="table-scroll"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function displaySource(source){if(!source)return 'Unavailable';const marker='/data_preflight/';const index=source.indexOf(marker);return index>=0?source.slice(index+1):source}
