import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import ScientificMap from '../components/ScientificMap'
import BundleErrors from '../components/BundleErrors'
import { Accordion, DataState, StatusBadge } from '../components/UI'
import useRemoteData from '../hooks/useRemoteData'
import { contextApi, demoApi, evidenceApi, followUpApi, investigationApi, loadCaseBundle, samplingApi } from '../services/api'

const colors={A:'#F97316',B:'#2563EB',C:'#16A34A',D:'#9333EA'}

export default function InvestigationWorkspace() {
  const {caseId}=useParams(), navigate=useNavigate(), demoStarted=useRef(false)
  const [open,setOpen]=useState({evidence:true,sources:true,decision:true,next:false}), [action,setAction]=useState({busy:false,error:''})
  useEffect(()=>{if(caseId==='demo'&&!demoStarted.current){demoStarted.current=true;demoApi.loadWigger().then(result=>navigate(`/investigations/${result.case_id}`,{replace:true})).catch(error=>setAction({busy:false,error:error.message}))}},[caseId,navigate])
  const remote=useRemoteData(()=>caseId==='demo'?Promise.resolve(null):loadCaseBundle(caseId),[caseId])
  if((caseId==='demo'&&!action.error)||remote.status==='LOADING')return <DataState status="LOADING" title="Loading scientific investigation" message="Retrieving persisted case data and validated map layers."/>
  if(remote.status==='ERROR'||!remote.data)return <><BundleErrors errors={{investigation:action.error?new Error(action.error):remote.error}} onRetry={()=>caseId==='demo'?demoApi.loadWigger().then(result=>navigate(`/investigations/${result.case_id}`,{replace:true})).catch(error=>setAction({busy:false,error:error.message})):remote.reload()}/><DataState status="ERROR" title="Investigation unavailable" message={action.error||remote.error?.message}/></>
  const bundle=remote.data, caseData=bundle.case, historical=caseData?.metadata?.historical_observation
  const sites=(bundle.sites||[]).map(s=>({...s,name:s.label,type:s.site_type,color:colors[s.label?.replace('Site ','')]||'#64748b'})), assessments=bundle.assessments||[]
  const latestRun=bundle.runs?.at(-1), decision=bundle.decision
  const detection=sites.find(site=>site.id===caseData.detection_site_id), detectionValidated=['MATCHED','VERIFIED'].includes(detection?.validation_status)
  const toggle=k=>setOpen({...open,[k]:!open[k]})
  async function act(operation){setAction({busy:true,error:''});try{await operation();await remote.reload();setAction({busy:false,error:''});return true}catch(error){setAction({busy:false,error:error.message});return false}}
  const steps=[['Detection site',detectionValidated,'Register a verified detection location'],['Evidence',Boolean(bundle.evidence?.length),'Add observed evidence'],['Source hypotheses',Boolean(bundle.zones?.length&&bundle.zones.every(zone=>['MATCHED','VERIFIED'].includes(zone.validation_status))),'Register at least one candidate zone'],['Candidate comparison',Boolean(bundle.comparison?.candidates?.length),'Generate candidate sites after hypotheses exist'],['Sampling decision',Boolean(decision&&decision.status!=='INSUFFICIENT_DATA'),'Evaluate and persist a sampling decision']]
  return <div className="workspace"><div className="workspace-map"><ScientificMap compact sites={sites} mapData={bundle.map} error={bundle.errors?.map} onRetry={remote.reload} title={caseData?.metadata?.name||'Scientific investigation'}/></div><aside className="investigation-panel"><div className="workspace-heading"><div><h1>Scientific investigation</h1><p>{caseData?.metadata?.name||`Case ${caseId.slice(0,8)}`}</p></div><StatusBadge value={decision?.status||'NOT_EVALUATED'}/></div>
    <BundleErrors errors={bundle.errors} onRetry={remote.reload}/>
    {(!detectionValidated||!bundle.zones?.length||bundle.zones.some(zone=>zone.validation_status==='NOT_VERIFIED'))&&<div className="warning-box">Scientific recommendation prerequisites are incomplete: the detection location and source hypotheses require supported network validation. A known reach ID alone does not verify user-entered data.</div>}
    <div className="notice"><strong>Detection validation: {detection?.validation_status||'Unavailable'}</strong><p>{detection?.metadata?.validation_reason||'See persisted detection network provenance.'}</p></div>
    <div className="workspace-summary"><span><small>Target species</small><strong><i>{caseData.target_taxon}</i></strong></span><span><small>Detection site</small><strong>{sites.find(s=>s.site_type==='DETECTION_SITE')?.label||'Unavailable'}</strong></span><span><small>Evidence status</small><strong>{!bundle.evidence?.length?'Additional information required':bundle.zones?.length?'Assessment available':'Hypotheses required'}</strong></span></div>
    <div className="workflow-status" aria-label="Scientific workflow status">{steps.map(([label,complete,next])=><div key={label} className={complete?'complete':'required'}><StatusBadge value={complete?'READY':'NOT_EVALUATED'}/><span><strong>{label}</strong><small>{complete?'Completed':next}</small></span></div>)}</div>
    <Accordion title="Detection Evidence" open={open.evidence} onToggle={()=>toggle('evidence')}><div className="label-row"><StatusBadge value={bundle.evidence?.length?'READY':'UNKNOWN'}/><span>{bundle.evidence?.length||0} evidence item(s)</span></div><div className="detail-grid"><div><small>Species</small><strong>{caseData.target_taxon}</strong></div><div><small>Station</small><strong>{historical?.station||sites.find(s=>s.site_type==='DETECTION_SITE')?.label||'Unavailable'}</strong></div><div><small>Observation index</small><strong>{historical?.observation_index??'Unavailable'}</strong></div><div><small>Sampling date</small><strong>{caseData.observation_date}</strong></div><div><small>Historical state</small><strong>{historical?.state||'Unavailable'}</strong></div><div><small>Concentration</small><strong>{historical?.concentration_mol_l!=null?`${historical.concentration_mol_l} mol/L`:'Unavailable'}</strong></div></div>{bundle.context?.map(c=><div className="notice" key={c.provider}><strong>{c.provider}: {c.status}</strong><p>{c.limitations?.join(' ')}</p></div>)}<div className="button-row"><button className="button" disabled={action.busy||!bundle.evidence?.length||!bundle.zones?.length} onClick={()=>act(()=>evidenceApi.assess(caseId))}>Refresh evidence assessment</button><button className="button" disabled={action.busy} onClick={()=>act(()=>contextApi.collect(caseId,{radius_m:5000,weather_window_days:0}))}>Collect available context</button></div></Accordion>
    <Accordion title="Possible Sources" open={open.sources} onToggle={()=>toggle('sources')}><div className="zone-grid">{(bundle.zones||[]).map(zone=>{const result=assessments.find(a=>a.zone_id===zone.id);return <div key={zone.id}><strong>{zone.label}</strong><small>Root reach {zone.root_hyriv_id} · {zone.validation_status}</small>{result?<><p>Supports {result.summary.supports}; contradicts {result.summary.contradicts}; neutral {result.summary.neutral}; unknown {result.summary.unknown}</p>{result.assessments.map(a=><p key={a.evidence_id}><b>{a.compatibility}</b> · {a.rule_id||'No applicable rule'} · {a.reason}</p>)}</>:<p>{bundle.evidence?.length?'Assessment requires additional information.':'Evidence is required before assessment.'}</p>}</div>})}</div>{!bundle.zones?.length&&<p>No candidate zones are registered.</p>}<p>Manual hypotheses remain NOT_VERIFIED. Reach membership alone does not validate a scientific recommendation.</p>{sites.some(site=>site.id===caseData.detection_site_id&&site.hyriv_id===20446064)&&<><p>For a Site A Wigger demonstration, import the frozen Z1/Z2/Z3 topology and B/C/D reference sites. This reuses the detection network match only when coordinates also match frozen Site A. Observations remain as entered.</p><button className="button" disabled={action.busy} onClick={()=>act(()=>samplingApi.importWigger(caseId))}>Load frozen Wigger reference</button></>}<ZoneForm busy={action.busy} onSubmit={payload=>act(()=>samplingApi.createZone(caseId,payload))}/></Accordion>
    <Accordion title="Sampling Decision" open={open.decision} onToggle={()=>toggle('decision')} trailing={<StatusBadge value={decision?.status||'NOT_EVALUATED'}/>}><p>{decision?.rationale||'NOT_EVALUATED — register source hypotheses, generate candidates, then evaluate the sampling decision.'}</p>{decision&&<p>Candidate scope: {decision.candidate_scope}. {bundle.investigationRun&&`Investigation run: ${bundle.investigationRun.investigation_run_id}`}</p>}{bundle.comparison?.candidates?.length>0?<><SimpleCandidates candidates={bundle.comparison.candidates}/>{!decision&&<p>{bundle.generated?.decision_reason}</p>}</>:<p>No candidate comparison is available.</p>}<div className="button-row"><button className="button" disabled={action.busy||!bundle.zones?.length} onClick={()=>act(()=>samplingApi.generate(caseId))}>Generate candidate comparison</button><button className="button primary" disabled={action.busy||!bundle.zones?.length} onClick={()=>act(()=>samplingApi.decide(caseId))}>Evaluate sampling decision</button></div>{bundle.trace&&<Trace trace={bundle.trace}/>}</Accordion>
    <Accordion title="Next Steps" open={open.next} onToggle={()=>toggle('next')}><p>Register a real follow-up sample with assay, controls, replicate counts, collector source, and provenance.</p><FollowUpForm sites={sites} candidates={bundle.generated?.candidates||[]} busy={action.busy} onSubmit={payload=>act(()=>followUpApi.create(caseId,payload))}/><FollowUpList samples={bundle.followUps||[]}/><button className="button" disabled={action.busy||!bundle.zones?.length} onClick={()=>act(()=>investigationApi.reinvestigate(caseId,{}))}>Run reinvestigation</button>{latestRun&&<p>Latest run: {latestRun.status} · {latestRun.investigation_run_id}</p>}</Accordion>
    {action.error&&<div className="error-banner">{action.error}</div>}
  </aside></div>
}

function SimpleCandidates({candidates}){return <div className="table-scroll"><table><thead><tr><th>Reach</th><th>Signature</th><th>Distinguished pairs</th><th>Pair score</th><th>Distance</th></tr></thead><tbody>{candidates.map(c=><tr key={c.hyriv_id}><td>{c.hyriv_id}</td><td>[{c.signature.join(', ')}]</td><td>{c.distinguished_hypothesis_pairs?.map(pair=>pair.join(' vs ')).join('; ')||'None'}</td><td>{c.pair_separation_score}</td><td>{c.network_distance_km!=null?`${c.network_distance_km.toFixed(3)} km`:'Unavailable'}</td></tr>)}</tbody></table></div>}
function Trace({trace}){return <div className="trace"><h3>Decision trace</h3><p><b>Rules:</b> {trace.rules_applied?.join(', ')||'None'}</p><p><b>Assumptions:</b> {trace.assumptions?.join(' ')}</p><p><b>Limitations:</b> {trace.limitations?.join(' ')}</p></div>}
function ZoneForm({busy,onSubmit}){const [form,setForm]=useState({label:'',root_hyriv_id:'',reach_ids:''});async function submit(event){event.preventDefault();const reachIds=form.reach_ids.split(',').map(value=>Number(value.trim()));if(await onSubmit({label:form.label,root_hyriv_id:Number(form.root_hyriv_id),reach_ids:reachIds,validation_status:'NOT_VERIFIED',metadata:{entry_method:'frontend'}}))setForm({label:'',root_hyriv_id:'',reach_ids:''})}return <form className="follow-up-form" onSubmit={submit}><strong>Register source hypothesis</strong><input required aria-label="Hypothesis label" placeholder="Hypothesis label" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/><input required min="1" type="number" aria-label="Root HydroRIVERS reach ID" placeholder="Root HydroRIVERS reach ID" value={form.root_hyriv_id} onChange={e=>setForm({...form,root_hyriv_id:e.target.value})}/><input required aria-label="Hypothesis reach IDs" placeholder="Reach IDs, comma separated" value={form.reach_ids} onChange={e=>setForm({...form,reach_ids:e.target.value})}/><button className="button" disabled={busy}>Register hypothesis</button></form>}
function FollowUpList({samples}){return samples.length?<div className="table-scroll"><table><thead><tr><th>Sampled</th><th>Reach</th><th>Replicates</th><th>Assay</th><th>Controls</th></tr></thead><tbody>{samples.map(sample=><tr key={sample.id}><td>{new Date(sample.sampled_at).toLocaleString()}</td><td>{sample.hyriv_id}</td><td>{sample.positive_replicates}/{sample.replicate_count}</td><td>{sample.assay}</td><td>{sample.controls_status}</td></tr>)}</tbody></table></div>:<div className="notice">No follow-up samples have been registered.</div>}
function FollowUpForm({sites,candidates,busy,onSubmit}){const initial={reference:'',sampled_at:'',replicate_count:1,positive_replicates:0,assay:'',controls_status:'',collector_source:''};const [form,setForm]=useState(initial);const options=[...sites.map(s=>({value:`site:${s.id}`,label:s.label,hyriv_id:s.hyriv_id})),...candidates.map(c=>({value:`candidate:${c.hyriv_id}`,label:`Candidate reach ${c.hyriv_id}`,hyriv_id:c.hyriv_id}))];async function submit(e){e.preventDefault();const target=options.find(o=>o.value===form.reference);if(!target)return;const isSite=form.reference.startsWith('site:');const saved=await onSubmit({sampling_site_id:isSite?form.reference.slice(5):null,candidate_reference:isSite?null:`HYRIV_ID:${target.hyriv_id}`,hyriv_id:target.hyriv_id,sampled_at:new Date(form.sampled_at).toISOString(),replicate_count:+form.replicate_count,positive_replicates:+form.positive_replicates,concentration:null,concentration_unit:null,assay:form.assay,controls_status:form.controls_status,collector_source:form.collector_source,provenance:{entry_method:'frontend'},notes:null});if(saved)setForm(initial)}return <form className="follow-up-form" onSubmit={submit}><select required value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}><option value="">Select sampled site</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><input required type="datetime-local" value={form.sampled_at} onChange={e=>setForm({...form,sampled_at:e.target.value})}/><div className="form-row"><input required min="1" type="number" aria-label="Replicate count" value={form.replicate_count} onChange={e=>setForm({...form,replicate_count:e.target.value})}/><input required min="0" max={form.replicate_count} type="number" aria-label="Positive replicates" value={form.positive_replicates} onChange={e=>setForm({...form,positive_replicates:e.target.value})}/></div><input required placeholder="Assay" value={form.assay} onChange={e=>setForm({...form,assay:e.target.value})}/><input required placeholder="Controls status" value={form.controls_status} onChange={e=>setForm({...form,controls_status:e.target.value})}/><input required placeholder="Collector source" value={form.collector_source} onChange={e=>setForm({...form,collector_source:e.target.value})}/><button className="button" disabled={busy||!options.length}>Register follow-up sample</button></form>}
