import { Plus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { DataState, PageHeader, StatusBadge } from '../components/UI'
import useRemoteData from '../hooks/useRemoteData'
import { casesApi, loadCaseIndex } from '../services/api'

const initial = { name:'', species:'', latitude:'', longitude:'', hyrivId:'', date:'', replicates:[''], metadata:'' }

function NewInvestigationForm({ onClose, onCreated }) {
  const [form,setForm] = useState(initial); const [errors,setErrors] = useState({}); const [notice,setNotice] = useState(''); const [submitting,setSubmitting]=useState(false)
  const set = (key,value) => setForm({...form,[key]:value})
  async function validate(e){e.preventDefault(); const next={}; ['name','species','latitude','longitude','hyrivId','date'].forEach(k=>{if(!form[k]) next[k]='Required'}); if(form.latitude && (+form.latitude < -90 || +form.latitude > 90)) next.latitude='Enter a latitude from -90 to 90'; if(form.longitude && (+form.longitude < -180 || +form.longitude > 180)) next.longitude='Enter a longitude from -180 to 180'; if(form.date&&form.date>new Date().toISOString().slice(0,10))next.date='Observation date cannot be in the future'; if(form.replicates.some(result=>!result)&&form.replicates.some(Boolean))next.replicates='Select a result for every replicate or remove unrecorded rows'; setErrors(next); if(Object.keys(next).length)return; setSubmitting(true);setNotice('');try{const recorded=form.replicates.filter(Boolean);const created=await casesApi.create({target_taxon:form.species,observation_date:form.date,detection_site_latitude:+form.latitude,detection_site_longitude:+form.longitude,detection_site_hyriv_id:+form.hyrivId,metadata:{name:form.name,additional_metadata:form.metadata},initial_evidence:recorded.length?[{evidence_type:'edna_observation',source:'frontend investigation form',value:{replicate_results:recorded,assay_metadata:form.metadata||null},observed_at:`${form.date}T00:00:00Z`,quality:null,provenance:{entry_method:'manual',observation_class:'USER_ENTERED'}}]:[]});onCreated(created.id)}catch(error){setNotice(error.message)}finally{setSubmitting(false)}}
  return <div className="modal-backdrop"><form className="investigation-form" onSubmit={validate}><div className="form-title"><div><h2>New Investigation</h2><p>Enter the initial observation. Scientific assessment occurs in the backend.</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close">×</button></div>
    <fieldset><legend>1. Species information</legend><label>Investigation name<input value={form.name} onChange={e=>set('name',e.target.value)}/>{errors.name&&<em>{errors.name}</em>}</label><label>Target species<input value={form.species} onChange={e=>set('species',e.target.value)}/>{errors.species&&<em>{errors.species}</em>}</label></fieldset>
    <fieldset><legend>2. Detection location</legend><div className="form-row"><label>Latitude<input type="number" step="any" value={form.latitude} onChange={e=>set('latitude',e.target.value)}/>{errors.latitude&&<em>{errors.latitude}</em>}</label><label>Longitude<input type="number" step="any" value={form.longitude} onChange={e=>set('longitude',e.target.value)}/>{errors.longitude&&<em>{errors.longitude}</em>}</label></div><label>Verified HydroRIVERS reach ID<input type="number" value={form.hyrivId} onChange={e=>set('hyrivId',e.target.value)}/>{errors.hyrivId&&<em>{errors.hyrivId}</em>}</label></fieldset>
    <fieldset><legend>3. Sampling date</legend><label>Date<input type="date" max={new Date().toISOString().slice(0,10)} value={form.date} onChange={e=>set('date',e.target.value)}/>{errors.date&&<em>{errors.date}</em>}</label></fieldset>
    <fieldset><legend>4. Replicate observations</legend>{errors.replicates&&<em>{errors.replicates}</em>}{form.replicates.map((result,index)=><div key={index}><label>Replicate {index+1}<select value={result} onChange={e=>set('replicates',form.replicates.map((value,i)=>i===index?e.target.value:value))}><option value="">Select recorded result</option><option>Positive</option><option>Negative</option><option>Invalid</option></select></label><button type="button" className="button" onClick={()=>set('replicates',form.replicates.filter((_,i)=>i!==index))}>Remove replicate {index+1}</button></div>)}<button type="button" className="button" onClick={()=>set('replicates',[...form.replicates,''])}>Add replicate</button></fieldset>
    <fieldset><legend>5. Additional evidence and metadata</legend><label>Laboratory or assay metadata<textarea value={form.metadata} onChange={e=>set('metadata',e.target.value)} placeholder="Optional source-provided metadata"/></label></fieldset>
    {notice&&<p className="form-notice">{notice}</p>}<div className="form-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={submitting}>{submitting?'Creating…':'Create investigation'}</button></div>
  </form></div>
}

export default function Investigations({ formOpen = false }) {
  const navigate=useNavigate(); const remote=useRemoteData(loadCaseIndex,[]); const records=useMemo(()=>remote.data?.cases||[],[remote.data])
  const [showForm,setShowForm]=useState(formOpen); const [search,setSearch]=useState(''); const [workflow,setWorkflow]=useState(''); const [decision,setDecision]=useState(''); const [updated,setUpdated]=useState('')
  const filtered=useMemo(()=>records.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())&&(!workflow||r.status===workflow)&&(!decision||(r.scientificDecision?.status||'NOT_EVALUATED')===decision)&&(!updated||r.updated_at.slice(0,10)===updated)),[records,search,workflow,decision,updated])
  return <div className="page-container"><PageHeader title="Investigations" description="Investigate uncertain detections and manage scientific decisions." action={<button className="button primary" onClick={()=>setShowForm(true)}><Plus size={16}/> New investigation</button>}/>
    <div className="filters"><label className="search"><Search size={17}/><input aria-label="Search investigations" placeholder="Search by investigation, species, or site" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Workflow status<select value={workflow} onChange={e=>setWorkflow(e.target.value)}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="UNDER_REVIEW">Under review</option><option value="COMPLETED">Completed</option><option value="ARCHIVED">Archived</option></select></label><label>Scientific decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">All decisions</option>{['RECOMMEND','TIE','ABSTAIN','INSUFFICIENT_DATA','NOT_EVALUATED'].map(x=><option key={x}>{x}</option>)}</select></label><label>Last updated<input type="date" value={updated} onChange={e=>setUpdated(e.target.value)}/></label><button className="text-button" onClick={()=>{setSearch('');setWorkflow('');setDecision('');setUpdated('')}}>Clear filters</button></div>
    <div className="table-card"><div className="table-scroll"><table><thead><tr>{['Investigation ID and Name','Target Species','Detection Site','Workflow Status','Scientific Decision','Last Updated','Open Investigation'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.metadata?.name||`Investigation ${r.id.slice(0,8)}`}</strong><small className="block">{r.id}</small></td><td><i>{r.target_taxon}</i></td><td>{r.detectionSiteLabel}</td><td>{r.status}</td><td><StatusBadge value={r.scientificDecision?.status||'NOT_EVALUATED'}/></td><td>{new Date(r.updated_at).toLocaleDateString()}</td><td><Link to={`/investigations/${r.id}`}>Open</Link></td></tr>)}</tbody></table></div>{remote.status==='LOADING'?<DataState status="LOADING" title="Loading investigations" message="Requesting persisted records."/>:(remote.status==='ERROR'||remote.status==='UNAVAILABLE')?<DataState status="ERROR" title="Backend unavailable" message={remote.error?.message}/>:!filtered.length&&<DataState title="No investigations match these filters" message="Clear filters or create a new investigation." action={<button className="button primary" onClick={()=>setShowForm(true)}>New investigation</button>}/>}</div>
    <p className="page-note">Workflow status and scientific decision status are displayed separately.</p>{showForm&&<NewInvestigationForm onClose={()=>setShowForm(false)} onCreated={id=>navigate(`/investigations/${id}`)}/>}</div>
}
