import { Download } from 'lucide-react'
import { reportSections } from '../data/appData'
import { StatusBadge } from '../components/UI'
import ScientificMap from '../components/ScientificMap'
import BundleErrors from '../components/BundleErrors'
import { useEffect, useMemo, useState } from 'react'
import useRemoteData from '../hooks/useRemoteData'
import { casesApi, loadCaseBundle } from '../services/api'

const Section=({id,title,children})=><section id={id} className="report-section"><h2>{title}</h2>{children}</section>

export default function Reports(){
  const casesRemote=useRemoteData(casesApi.list,[]), cases=useMemo(()=>casesRemote.data?.cases||[],[casesRemote.data]), [selected,setSelected]=useState('')
  useEffect(()=>{if(!selected&&cases.length)setSelected(cases[0].id)},[cases,selected])
  const bundleRemote=useRemoteData(()=>selected?loadCaseBundle(selected):Promise.resolve(null),[selected]), bundle=bundleRemote.data?.case?.id===selected?bundleRemote.data:{}, caseData=bundle.case
  const decision=bundle.decision, historical=caseData?.metadata?.historical_observation
  const evidenceById=Object.fromEntries((bundle.evidence||[]).map(item=>[item.id,item])), assessmentRows=(bundle.assessments||[]).flatMap(zone=>zone.assessments.map(item=>{const evidence=evidenceById[item.evidence_id]||{};return [zone.zone_label,evidence.evidence_type||'Unavailable',displaySource(evidence.source),item.rule_id||'No applicable rule',item.compatibility,item.reason,evidence.quality||'UNASSESSED']}))
  const detectionSite=(bundle.sites||[]).find(site=>site.id===caseData?.detection_site_id), networkFeatures=bundle.map?.river_network?.features||[], networkLength=networkFeatures.reduce((total,feature)=>total+Number(feature.properties?.LENGTH_KM||0),0)
  const eligible=(decision?.recommended_site_ids||[]).map(id=>(bundle.sites||[]).find(site=>site.id===id)?.label||bundle.comparison?.candidates?.find(candidate=>candidate.site_id===id)?.label||(decision.candidate_scope==='GENERATED_REPRESENTATIVES'?`Generated reach ${bundle.comparison?.candidates?.find(candidate=>candidate.site_id===id)?.hyriv_id??id}`:`Sampling site ${id}`))
  const oneHealthRows=(bundle.oneHealth?.pathways||[]).map(pathway=>[pathway.monitoring_finding?.status||'UNKNOWN',pathway.monitoring_finding?.statement||'Unavailable',pathway.possible_monitoring_action?.statement||'Unavailable'])
  const missing=[...(!['MATCHED','VERIFIED'].includes(detectionSite?.validation_status)?['Detection location validation']:[]),...(bundle.zones?.some(zone=>zone.validation_status==='NOT_VERIFIED')?['Source hypothesis validation']:[]),...Object.keys(bundle.errors||{}).map(key=>`${key} unavailable`),...(!bundle.evidence?.length?['Observed evidence']:[]),...(!bundle.zones?.length?['Source hypotheses']:[]),...(!bundle.comparison?.candidates?.length?['Candidate comparison']:[]),...(!decision?['Persisted decision']:[]),...(!bundle.trace?['Decision trace']:[])]
  const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})
  return <div className="reports-layout"><aside className="report-toc"><h1>Reports</h1><p>Draft investigation records and exportable methods.</p><strong>In this report</strong>{reportSections.map(([id,title])=><button key={id} onClick={()=>scroll(id)}>{title}</button>)}</aside><div className="report-column"><div className="report-controls"><label>Scientific report<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select investigation</option>{cases.map(c=><option key={c.id} value={c.id}>{c.metadata?.name||c.target_taxon}</option>)}</select></label><StatusBadge value={decision?.status||'NOT_EVALUATED'}/><button className="button primary" disabled={!caseData||bundleRemote.status==='LOADING'||Boolean(bundleRemote.error)||Boolean(Object.keys(bundle.errors||{}).length)} onClick={()=>window.print()}><Download size={15}/> Export PDF</button></div><BundleErrors errors={{...bundle.errors,...(casesRemote.error?{cases:casesRemote.error}:{}),...(bundleRemote.error?{report:bundleRemote.error}:{})}} onRetry={()=>{casesRemote.reload();bundleRemote.reload()}}/>{bundleRemote.status==='LOADING'||!caseData?<div className="report-document"><p>{bundleRemote.status==='LOADING'?'Loading report data…':'No investigation selected or backend unavailable.'}</p></div>:<article className="report-document"><header><div><h1>{caseData.metadata?.name||`Investigation ${caseData.id.slice(0,8)}`}</h1><p>Draft investigation record for an uncertain freshwater eDNA detection.</p></div><StatusBadge value={decision?.status||'NOT_EVALUATED'}/></header>
    <div className="report-meta"><span><small>Report status</small><strong>Draft</strong></span><span><small>Observation date</small><strong>{caseData.observation_date}</strong></span><span><small>Prepared for</small><strong>Scientific review</strong></span><span><small>Scientific decision</small><strong>{decision?.status||'NOT_EVALUATED'}</strong></span></div>
    <Section id="summary" title="Investigation Summary">{missing.length>0&&<div className="warning-box">Draft — missing or unavailable: {missing.join('; ')}.</div>}<p>A structured record for evaluating an uncertain eDNA detection and identifying a defensible follow-up action.</p></Section>
    <Section id="detection" title="Original eDNA Detection"><SimpleTable heads={['Field','Value']} rows={[['Species',caseData.target_taxon],['Station',historical?.station||detectionSite?.label||'Unavailable'],['Observation index',historical?.observation_index??'Unavailable'],['Detection site reach',detectionSite?.hyriv_id??'Unavailable'],['Detection validation',detectionSite?.validation_status||'Unavailable'],['Validation reason',detectionSite?.metadata?.validation_reason||'See persisted network provenance'],['Detection provenance',detectionSite?.metadata?.network_source?displaySource(detectionSite.metadata.network_source):'Unavailable'],['Coordinates',detectionSite?`${detectionSite.latitude}, ${detectionSite.longitude}`:'Unavailable'],['Sampling date',caseData.observation_date],['Laboratory or assay metadata',caseData.metadata?.additional_metadata||'Unavailable'],['Historical state',historical?.state||'Unavailable'],['Concentration',historical?.concentration_mol_l!=null?`${historical.concentration_mol_l} mol/L`:'Unavailable'],['Replicate and assay metadata',(bundle.evidence||[]).some(item=>Array.isArray(item.value?.replicate_results))?'See persisted replicate observations below':'Unavailable in the persisted evidence']]}/>{(bundle.evidence||[]).some(item=>Array.isArray(item.value?.replicate_results))&&<SimpleTable heads={['Observation source','Replicate','Recorded result','Assay metadata','Provenance']} rows={bundle.evidence.flatMap(item=>(Array.isArray(item.value?.replicate_results)?item.value.replicate_results:[]).map((result,index)=>[item.provenance?.entry_method==='manual'?'User-entered observation':displaySource(item.source),index+1,result,item.value.assay_metadata?typeof item.value.assay_metadata==='string'?item.value.assay_metadata:JSON.stringify(item.value.assay_metadata):'Unavailable',JSON.stringify(item.provenance)]))}/>}</Section>
    <Section id="evidence" title="Evidence Assessment">{Boolean(bundle.evidence?.length)&&<SimpleTable heads={['Evidence type','Source','Observed','Quality','Recorded value','Provenance']} rows={bundle.evidence.map(item=>[item.evidence_type,displaySource(item.source),item.observed_at?new Date(item.observed_at).toLocaleString():'Unavailable',item.quality||'UNASSESSED',JSON.stringify(item.value),JSON.stringify(item.provenance)])}/>} {assessmentRows.length?<><SimpleTable heads={['Zone','Evidence','Source','Rule','Result','Explanation','Quality']} rows={assessmentRows}/>{assessmentRows.every(row=>row[4]==='UNKNOWN')&&<div className="warning-box">Evidence was evaluated, but the available validated rules were insufficient to determine compatibility.</div>}</>:<div className="warning-box">{!bundle.evidence?.length?'Evidence records are missing; no assessment can be performed.':!bundle.zones?.length?'Source hypotheses are missing; evidence cannot yet be compared.':'No persisted assessment result is available.'}</div>}</Section>
    <Section id="hydrology" title="Hydrological Investigation"><p>{bundle.zones?.length?`${bundle.zones.length} candidate zones and ${bundle.sites?.length||0} sites are registered. Validation is shown for each hypothesis; registration alone does not verify user data. The validated map contains ${networkFeatures.length} reaches totaling ${networkLength.toFixed(2)} km.`:'No candidate zones are registered.'}</p><p>Directed connectivity establishes a possible mapped transport pathway. It does not confirm the biological source.</p></Section>
    <Section id="map" title="Investigation Map">{bundle.map?.available?<ScientificMap compact mapData={bundle.map} error={bundle.errors?.map} onRetry={bundleRemote.reload} title={caseData.metadata?.name||'Investigation geography'}/>:<div className="report-map"><strong>Verified spatial data unavailable</strong><small>{bundle.map?.unavailable_reason||'No verified geometry is linked to this investigation.'}</small></div>}</Section>
    <Section id="sources" title="Competing Source Explanations">{bundle.zones?.length?<SimpleTable heads={['Zone','Root reach','Reach count','Validation','Provenance']} rows={bundle.zones.map(z=>[z.label,z.root_hyriv_id,z.reach_ids.length,z.validation_status,JSON.stringify(z.metadata)])}/>:<div className="warning-box">No source hypotheses are registered.</div>}</Section>
    <Section id="candidates" title="Candidate Sampling Comparison">{decision&&<p>Candidate scope: {decision.candidate_scope}. {bundle.investigationRun&&`Investigation run: ${bundle.investigationRun.investigation_run_id}`}</p>}{bundle.comparison?.candidates?.length?<><p>{decision?.candidate_scope==='REGISTERED_SITES'?'The comparison uses registered sampling sites evaluated for this decision.':'The generated reaches are one representative per useful, validated upstream reachability signature. A zero-separation signature is excluded; the nearest reach to the detection site represents each remaining signature. This distance chooses a representative within a class and is not a biological ranking. Generated reaches are not automatically registered field sites.'}</p><SimpleTable heads={['Reach','Signature','Distinguished pairs','Pair separation','Validation']} rows={bundle.comparison.candidates.map(c=>[c.hyriv_id,`[${c.signature.join(', ')}]`,c.distinguished_hypothesis_pairs?.map(pair=>pair.join(' vs ')).join('; ')||'None',c.pair_separation_score,c.validation_status||'See decision trace'])}/><p>Eligibility for a registered-site field recommendation also requires a scientifically valid registered site and validated zone network state. The score assumes ideal binary outcomes and does not estimate detection probability.</p></>:<div className="warning-box">Candidate comparison is unavailable. Register source hypotheses before generating candidates.</div>}</Section>
    <Section id="decision" title="Sampling Decision and Scientific Reasoning"><div className="warning-box"><strong>{decision?.status||'NOT_EVALUATED'}</strong><p>{decision?.rationale||'No persisted scientific decision exists. Register hypotheses and candidate sites, then evaluate the sampling decision.'}</p></div>{bundle.trace&&<><p>Decision trace ID: {bundle.trace.decision_id}</p><p>Rules applied: {bundle.trace.rules_applied?.join(', ')||'Unavailable'}</p><p>Evidence used: {bundle.trace.evidence_used?.join(', ')||'None recorded'}</p>{bundle.trace.hydrology_checks?.length>0&&<SimpleTable heads={['Hydrology check']} rows={bundle.trace.hydrology_checks.map(check=>[JSON.stringify(check)])}/>}<p>Trace recorded: {bundle.trace.created_at||'Unavailable'}</p></>}</Section>
    <Section id="followup" title="Follow-up Sampling"><p>{eligible.length?`Eligible sites under the persisted decision: ${eligible.join(', ')}.`:'No persisted follow-up recommendation is available.'} A negative sample does not prove absence and a positive sample does not by itself prove the exact source.</p>{bundle.followUps?.length?<SimpleTable heads={['Sampled','Reach','Positive / total','Assay','Controls','Collector']} rows={bundle.followUps.map(sample=>[new Date(sample.sampled_at).toLocaleString(),sample.hyriv_id,`${sample.positive_replicates} / ${sample.replicate_count}`,sample.assay,sample.controls_status,sample.collector_source])}/>:<p>{bundle.errors?.followUps?'Follow-up samples unavailable.':'No follow-up samples have been registered.'}</p>}</Section>
    <Section id="context" title="Environmental and One Health Context"><p>Context does not independently establish source presence, pollution, disease, or human-health risk.</p>{bundle.context?.length?<SimpleTable heads={['Provider','Availability','Compatibility']} rows={bundle.context.map(c=>[c.provider,c.status,c.compatibility])}/>:<p>{bundle.errors?.context?'Environmental context unavailable.':'No environmental context records were collected for this report.'}</p>}{oneHealthRows.length>0&&<SimpleTable heads={['Status','Supported monitoring finding','Possible monitoring action']} rows={oneHealthRows}/>}</Section>
    <Section id="next" title="Next Steps"><p>{!bundle.evidence?.length?'Record observed evidence and its provenance. ':''}{!bundle.zones?.length?'Register scientifically supported source hypotheses. ':''}{!bundle.generated?.candidates?.length?'Generate a candidate comparison after hypotheses are available. ':''}{!decision?'Evaluate and persist a sampling decision when prerequisites are complete. ':''}{decision&&!bundle.followUps?.length?'Register actual follow-up samples when field results are available.':''}</p></Section>
    <Section id="data" title="Data Sources"><SimpleTable heads={['Source','Availability']} rows={[['Backend investigation records','Loaded'],['Verified HydroRIVERS spatial data',bundle.map?.available?displaySource(bundle.map.provenance?.river_network)||'Loaded with EPSG:4326 provenance':'Unavailable'],['Observation provenance',historical?.provenance?.edna_source?displaySource(historical.provenance.edna_source):(bundle.evidence?.length?'Stored with evidence records':'Unavailable')],['Scientific rules',(bundle.trace?.rules_applied||[]).join(', ')||'No persisted decision trace']]}/></Section>
    <Section id="assumptions" title="Assumptions"><p>{bundle.trace?.assumptions?.join(' ')||'No decision-trace assumptions are available.'}</p></Section>
    <Section id="limitations" title="Limitations"><p>{bundle.trace?.limitations?.join(' ')||'No decision-trace limitations are available. No confidence score is inferred.'}</p></Section>
  </article>}</div></div>
}

function SimpleTable({heads,rows}){return <div className="table-scroll"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function displaySource(source){if(!source)return 'Unavailable';const marker='/data_preflight/';const index=source.indexOf(marker);return index>=0?source.slice(index+1):source}
